### ISSUE TITLE
WaitForControlledPodsRunning should log problematic pods

### ISSUE THREAD

**Issue by oxddr** [kubernetes/perf-tests#1014]
WaitForControlledPodsRunning measurement should log problematic pods, when it times out. In case there is more than let say 5 pods, it should print at most 5 of them.

Currently, figuring out which pod has failed is problematic and requires listing all pods from a certain deployment from scheduler logs to locate victim. 

/good-first-issue
/help-wanted
/area clusterloader

**Comment by vamossagar12** [comment]
hey @oxddr i can take this up. can you provide some details/examples that I can refer to plz?

**Comment by oxddr** [comment]
I happy to hear that. I have other work today, but I'll try to add more details tomorrow.

**Comment by wojtek-t** [comment]
/remove-lifecycle stale

@mborsz - do I understand correctly that you were already adding around that?

**Comment by wojtek-t** [comment]
/remove-lifecycle stale

@mborsz - would this be something useful for debugging?
