### ISSUE TITLE
Pod-startup-latency should be measured throughout whole load test

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/perf-tests#1024]
There is number of issues with the current way we measure the [pod-startup-latency slo](https://github.com/kubernetes/community/blob/master/sig-scalability/slos/pod_startup_latency.md):

1. We have a set artificial steps only to measure it while we should measure and assert on the all pods created throughout the load tests
2. We set artificial CPU/memory requests for the pods that we use to measure the pod-startup-latency (100m, 350M) in order to guarantee even distribution of the pods across all nodes (even though it's not a part of the official SLO)

We should experiment whether switching to containerd in our tests would allow to simplify measuring it and making our tests more aligned with the official SLO definition.

**Comment by mm4tt** [comment]
Another issue is that we use 5QPS for creating latency pods even though we officially support higher throughput.

**Comment by wojtek-t** [comment]
/remove-lifecycle stale

Back then I splitted the pod-startup-latency measurement to also produce the "Stateless" part of it and it seems it's broken now.
We should fix that as this will be needed anyway.

We may try to run an experiment where we will bump QPS limits on nodes and see if that will address the problems.

**Comment by wojtek-t** [comment]
This seems to be duplicate of https://github.com/kubernetes/perf-tests/issues/1311

Closing in favor of that one, as the other has a lot more information.
