### ISSUE TITLE
scalability-presubmit-project boskos pool is overutilized

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/perf-tests#1034]
We've got pinged a few times in the last month about this on slack. We added 5 projects but it doesn't seem to be enough

![5hBcbe06Out](https://user-images.githubusercontent.com/2604887/74030170-b0f1df80-49ae-11ea-80e5-246aece58e74.png)

We should add more projects to the pool, the increase usage is kind of expected as recently we added a lot of presubmits for release branches

**Comment by mm4tt** [comment]
/assign @oxddr 

Assigning to current scalability oncall

**Comment by mm4tt** [comment]
/assign @jkaniuk 

And the next oncall as Janek finishes his shift in a few hours

**Comment by oxddr** [comment]
/assign @jprzychodzen 

Jakub has a script to be tested to automate project creation. This is a good opportunity to test it.

**Comment by jprzychodzen** [comment]
Done with #16188

**Comment by mm4tt** [comment]
Thanks @jprzychodzen!
Closing this one for now, the current scalability-presubmit-project pool issues are tracked in https://github.com/kubernetes/test-infra/issues/14697
