### ISSUE TITLE
How to enable prometheus in density test?

### ISSUE THREAD

**Issue by Sakuralbj** [kubernetes/perf-tests#1059]
I want to get APIResponsiveness result in density test. Should I install prometheus by myself or density test will do it automatically? 
I use test config [density](https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/testing/density/config.yaml) and  kubemark for test.
```
ENABLE_PROMETHEUS_API_RESPONSIVENESS := DefaultParam .ENABLE_PROMETHEUS_API_RESPONSIVENESS true.
```
Results:
```
W0218 10:23:37.370790   27340 prometheus_measurement.go:59] APIResponsivenessPrometheus: Prometheus is disabled, skipping the measurement!
W0218 10:23:37.370810   27340 prometheus_measurement.go:59] APIResponsivenessPrometheusSimple: Prometheus is disabled, skipping the measurement!
```

By the way, can perf-tests be used for testing real nodes? If so,should I set provider to local?
Thanks for any help!

**Comment by wojtek-t** [comment]
https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/pkg/prometheus/prometheus.go#L56

**Comment by Sakuralbj** [comment]
> https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/pkg/prometheus/prometheus.go#L56

Thank you for your guide!  If I want to do the test using real nodes but not kubemark,what should I do? Can I set param provider to local?

**Comment by Sakuralbj** [comment]
Where is kubemarkServiceMonitors ?  I don't see kubemark directory in perf-tests/clusterloader2/pkg/prometheus/manifests. @wojtek-t @mm4tt 
![image](https://user-images.githubusercontent.com/42128207/74820558-370e0e80-533d-11ea-93c0-912a8905a62c.png)
![image](https://user-images.githubusercontent.com/42128207/74820587-44c39400-533d-11ea-88af-48a3a2549fdd.png)
![image](https://user-images.githubusercontent.com/42128207/74820676-658be980-533d-11ea-8177-91171589bc3a.png)
![image](https://user-images.githubusercontent.com/42128207/74820766-83f1e500-533d-11ea-8dc1-7cdfcd1e2ba8.png)

**Comment by mm4tt** [comment]
Good catch, I think it's some leftover from one of the recent refactoring of that code. I'd appreciate if you could send a PR cleaning it up  (basically remove this logic from prometheus.go) :)

Regarding your other questions:

1. You can enable prometheus with `--enable-prometheus-server`flag (definition in the prometheus.go file that Wojtek linked). Clusterloader2 will set it up and tear down automatically
2. Clusterloader2 should be able to test any k8s cluster, real (e.g. gce, gke, aws cluster) or fake (e.g. kubemark)

**Comment by Sakuralbj** [comment]
> Good catch, I think it's some leftover from one of the recent refactoring of that code. I'd appreciate if you could send a PR cleaning it up (basically remove this logic from prometheus.go) :)
> 
> Regarding your other questions:
> 
> 1. You can enable prometheus with `--enable-prometheus-server`flag (definition in the prometheus.go file that Wojtek linked). Clusterloader2 will set it up and tear down automatically
> 2. Clusterloader2 should be able to test any k8s cluster, real (e.g. gce, gke, aws cluster) or fake (e.g. kubemark)

Thank you!  I'm not quite sure what  clean it up means. Is it mean we don't need to judge whether pc.iskubemark(), apply defaultServiceMonitors in all situation?
![image](https://tva1.sinaimg.cn/large/0082zybpgy1gc20sqbbr4j30t4096q3q.jpg)

**Comment by mm4tt** [comment]
As you noticed, there is no such thing as `kubemarkServiceMonitors`. By clean up I meant to remove the variable and all the code that uses it.

**Comment by Sakuralbj** [comment]
> As you noticed, there is no such thing as `kubemarkServiceMonitors`. By clean up I meant to remove the variable and all the code that uses it.

Ok,I'll do it.
