### ISSUE TITLE
Clusterloader2 tests are flaky due to NetworkProgrammingLatency measurement errors

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/perf-tests#1068]
I saw at least 2 runs where the tests failed with the following error:

```
[measurement call NetworkProgrammingLatency - NetworkProgrammingLatency error: got unexpected number of samples: 0]
```

E.g. https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/perf-tests/1064/pull-perf-tests-clusterloader2/1230261141716865025/

/assign @oxddr 

Janek, could you take a look? If it's hard to debug can we at least make NPL to not fail the test (it's still a WIP SLI).

**Comment by oxddr** [comment]
The error you see is a result of Prometheus not returning any samples to NPL query. This is unexpected, even if the returned values are rubbish ;) 

I'll have a look at that hopefully this week. 

/priority important-longterm
/area clusterloader

**Comment by oxddr** [comment]
Closing this one in favor of https://github.com/kubernetes/kubernetes/issues/82364

/close
