### ISSUE TITLE
SchedulingLatency metrics lost in 1.18 and master jobs

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/perf-tests#1074]
As reported in the discussion in https://github.com/kubernetes/perf-tests/pull/1061, master and 1.18 branch since last week the SchedulingLatency metrics are reported as 0s, e.g. https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1231113766444208131/artifacts/SchedulingMetrics_load_2020-02-22T07:39:26Z.json

It's nicely visible on the perd-dash:
### master
![cQAHfr3oK6P](https://user-images.githubusercontent.com/2604887/75094204-77fa6300-5589-11ea-8ec3-d90a8f9807fe.png)
### 1.18
![qeSpiQMOw4d](https://user-images.githubusercontent.com/2604887/75094399-f277b280-558a-11ea-9056-430466569f28.png)

Our older release tests are fine, e.g. 1.17:
![MR3W4CsfkiA](https://user-images.githubusercontent.com/2604887/75094235-9e200300-5589-11ea-8c52-dd1650d5e95c.png)

**Comment by mm4tt** [comment]
We should either fix that or switch to some other metrics given that the metrics that we currently scrape are deprecated, see https://github.com/kubernetes/perf-tests/pull/1061#issuecomment-589963192

**Comment by ingvagabund** [comment]
https://github.com/kubernetes/perf-tests/pull/1061#issuecomment-590500497

predicates/priorities are not part of the collected metrics string

**Comment by ingvagabund** [comment]
Due to https://github.com/kubernetes/kubernetes/pull/86584, both predicate/priority metrics are deprecated since 1.18:
- scheduling_algorithm_predicate_evaluation_seconds, replaced by framework_extension_point_duration_seconds[extenstion_point="Filter"]
- scheduling_algorithm_priority_evaluation_seconds, replaced by framework_extension_point_duration_seconds[extenstion_point="Score"]

**Comment by ingvagabund** [comment]
Opening https://github.com/kubernetes/kubernetes/pull/88485 to postpone the deprecation version to 1.19.

**Comment by ingvagabund** [comment]
@mm4tt metrics are popping back: http://perf-dash.k8s.io/#/?jobname=gce-100Nodes-master&metriccategoryname=Scheduler&metricname=SchedulingLatency&Operation=predicate_evaluation.
