### ISSUE TITLE
clusterloader2 support creation of explicit pod objects.

### ISSUE THREAD

**Issue by aakarshg** [kubernetes/perf-tests#1077]
Code for clusterloader2 is currently opinionated towards creation of controller objects, and this makes it very difficult to use the tool for creation of pod objects specifically. I've tried creation of pod objects and run into an error as follows:

```
E0224 14:40:11.218917   45568 wait_for_controlled_pods.go:283] WaitForControlledPodsRunning: create checker error: waiting for test-eejm2w-1/pod-2 error: try to selector fai
led, field selector not found                                                                                                                                                
E0224 14:40:11.302853   45568 wait_for_controlled_pods.go:283] WaitForControlledPodsRunning: create checker error: waiting for test-eejm2w-2/pod-4 error: try to selector fai
led, field selector not found                                                                                                                                                
E0224 14:40:11.533384   45568 wait_for_controlled_pods.go:283] WaitForControlledPodsRunning: create checker error: waiting for test-eejm2w-1/pod-7 error: try to selector fai
led, field selector not found                                                                                                                                                
E0224 14:40:11.554569   45568 wait_for_controlled_pods.go:283] WaitForControlledPodsRunning: create checker error: waiting for test-eejm2w-1/pod-8 error: try to selector fai
led, field selector not found  
```

Digging into code this is due to an assumption that the `controller` has a filed spec.selector - https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go#L152

Looking for any pointers to make changes so that clusterloader2 can support explicit pod object creation

**Comment by wojtek-t** [comment]
Creating "naked" pods is an anti-pattern in k8s. We don't want to support it.

**Comment by aakarshg** [comment]
> Creating "naked" pods is an anti-pattern in k8s. We don't want to support it.

Can you please elaborate? or point to any docs/blogs that can help me understand this?

**Comment by wojtek-t** [comment]
If a node goes down, you pod disappears.
All pods should be controlled by some controller (deployment, replicaset, statefulset,custom controller, ...)

**Comment by aakarshg** [comment]
Understood @wojtek-t thanks for explanation. So in that case which controller is used to determine the pods per node limit as per https://kubernetes.io/docs/setup/best-practices/cluster-large/#support ? 

Some more context: We try to test similar configurations, but in the past we've used naked pods and our own version of clusterloader. We're evaluating the clusterloader2 in this case to see if we can replicate creation of n naked pods....
