### ISSUE TITLE
Presubmits should be run on release branches. 

### ISSUE THREAD

**Issue by oxddr** [kubernetes/perf-tests#1092]
Context: [this PR](https://github.com/kubernetes/perf-tests/pull/1090) has been merged without running any tests. Changes to clusterloader2 have a potential to break things and presubmit is a cheap way to prevent at least trivial issues.

**Comment by oxddr** [comment]
/area clusterloader
/priority important-soon

Ideally configuration of those presubmits should be generated when, the new release branch is created.

**Comment by wojtek-t** [comment]
/remove-lifecycle rotten

@jkaniuk @mm4tt - FTR
