### ISSUE TITLE
Investigate making containerd an official scalability CRI recommendation

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/perf-tests#1110]
We've got a lot of premises that containerd performance is better comparing to docker. E.g. 

1. Pod throughput

    **Docker**
    http://perf-dash.k8s.io/#/?jobname=docker-node-throughput&metriccategoryname=E2E&metricname=PodStartup&Metric=pod_startup
    ![2aT6DcSAOYG](https://user-images.githubusercontent.com/2604887/75969747-ace2b000-5ecf-11ea-9108-bcf9961c88cb.png)

    **Containerd**
    http://perf-dash.k8s.io/#/?jobname=containerd-node-throughput&metriccategoryname=E2E&metricname=PodStartup&Metric=pod_startup
    ![W4MqW0DqV0C](https://user-images.githubusercontent.com/2604887/75969755-aeac7380-5ecf-11ea-9165-95956b8b3861.png)

2. Recent findings when working on merging density test into load test - https://github.com/kubernetes/perf-tests/issues/1007

We should investigate it more thoroughly, e.g. see what would be the impact of switching our scale tests to containerd. If those experiments turn out successful, we should consider making containerd an official SIG Scalability recommendation.

**Comment by mm4tt** [comment]
/remove-lifecycle rotten
We're still working on that

**Comment by wojtek-t** [comment]
/remove-lifecycle stale

That kind-of already happened, because we updated the default in startup scripts.
We should just clean up stuff a bit (our test configs - containerd is already a default) and then update the documentation.

**Comment by jprzychodzen** [comment]
Pending items

* Remove containerd specific present `preset-e2e-scalability-containerd`. It can be removed when branch 1.20 will be removed from supported branches. It will be about ~8 months from now.
* Update sig-scalability documentation. Expalining ContainerD vs Docker around https://github.com/kubernetes/community/tree/master/sig-scalability should cover this.

**Comment by wojtek-t** [comment]
FIxed.
