### ISSUE TITLE
Implement a post-submit job for building and pushing perf-dash image

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/perf-tests#1112]
We can take inspiration from the existing jobs for kubekins that does the same. See 
https://github.com/kubernetes/test-infra/blob/5ae038e4ff718367db1b7e9857e9f1b5ae2d61b5/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml#L431

Ref. https://github.com/kubernetes/perf-tests/pull/1088#issuecomment-595155270

**Comment by oxddr** [comment]
My comment from the PR:

> Ideally, we should have a better process for that. We could make it work similarly to kubekins where there is a post-submit job configured to automatically build and push a new image every time the relevant code changes. I'll file an issue for that

We've talked about it in the past and decided not to do anything, as perf-dash (in the current form) at some point is going to be replaced. On the other hand, building (and even rolling out) an image should be easy to do with Cloud Build.

**Comment by mm4tt** [comment]
Copying my comment as well :)

I think it shouldn't be more than ~2h of work (given that there is an existing post-submit we can just copy and tune to our needs). Given that it takes ~10-15min to build/push new perf-dash and we're pushing it 3rd time this month, I believe such investment would quickly pay-off.

**Comment by oxddr** [comment]
/assign 

I had an initial look at this, but I haven't found enough time to finish this. I'll try to have a look at this next week or so.

**Comment by mm4tt** [comment]
Thanks, @oxddr!
