### ISSUE TITLE
clusterloader2's Prometheus cannot connect to the apiserver

### ISSUE THREAD

**Issue by karim-manaouil** [kubernetes/perf-tests#1129]
I run clusterloader2 with "--enable-prometheus-server". Prometheus was successfully deployed and running but once I checked the generated report, the APIResponsivenessPrometheus results were empty. After openning the Prometheus web interface and heading to /targets page, it seems that Prometheus wasn't scrapping the apiserver and it failed to establish connection. I checked the RBAC and it was all fine, the prometheus object references the right serviceAccount and this last one is bound with a clusterRole that gives is access to the apiserver's /metric endpoint. [Here is a screenshot of the /targets of Prometheus](https://i.imgur.com/Ls4JYah.png).And here is the log trying to access the apiserver from within the Prometheus container using the bearer token:
```
/prometheus $ wget --header 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImhlZ0h2R3FZTHNyWTVKdWFHSklsV05XSVJxUHNNWVNsdkNBWnZaT1FDcVUifQ.eyJpc3MiOiJrdWJlcm5ldGVz
L3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJtb25pdG9yaW5nIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InByb21ldGhldX
MtazhzLXRva2VuLXFqaGh3Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InByb21ldGhldXMtazhzIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNl
LWFjY291bnQudWlkIjoiYjBmODIwODAtZWNlNy00MTY3LWJmOTctNDA2YzcwMDA3MWI4Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Om1vbml0b3Jpbmc6cHJvbWV0aGV1cy1rOHMifQ.rqWAoysjWyw2I2dNb2p
GgOf-F2zh3fEbtS7U8vomL-_KFkssyqyKkageIWDElhNwDoZZgwcX468U1wi0ptJTnc-CLr-HffdWFoncz5oh3-o9ifsTMa8QlsAM9816FdKMJxzGtmHwnCVDRJkVUb3ATh8ZAVJIGXr-C8HKHL_7xTX90M38iSh9UVCQ9
oymHTbVFkahHmBYgacNgDuFAcbdp4LA0SzSld6jCEztghRKVBBtrQ1-udqdV_UN7E3l6Y--pNxFqNaRGXXdnlAogxVkvx3D4FfKsahj5F_65t8vl6OSzPrIXMu9pM3FvPH9SEPlkE4VYBXV-K0qtEkMTrX1Sg' 10.158.
24.2:443/metrics
Connecting to 10.158.24.2:443 (10.158.24.2:443)
wget: can't connect to remote host (10.158.24.2): Connection refused
```

Do you have any clue why can't Prometheus scrap the apiserver ?

**Comment by pytimer** [comment]
@karim-manaouil  Does kube-apiserver listen on 443 port? I use `kubeadm` create Kubernetes cluster, and i update the master serviceMonitor endpoint, because the default kube-apiserver listen on 6443. You can check your master endpoint. `kubectl get servicemonitor -n monitoring master`.
