### ISSUE TITLE
[ClusterLoader2][NodeKiller] Refactor NodeKiller by adding 'provider' abstraction and move env specific calls over there

### ISSUE THREAD

**Issue by jprzychodzen** [kubernetes/perf-tests#1137]
Two provides should be implemented to consider this issue resolved
 *  one for GCP environment (currenly inlined in [clusterloader2/pkg/chaos](../tree/master/clusterloader2/pkg/chaos) code)
 *  one for fake (testing) environment

Resolving this will unlock adding Kubemark provider and unit testing Chaos Monkey/Node Killer.

/good-first-issue

**Comment by mcastellin** [comment]
As promised, following up on this one
/assign

**Comment by wojtek-t** [comment]
Closing as duplicte of https://github.com/kubernetes/perf-tests/issues/238
