### ISSUE TITLE
Perf-dash graphs for test-phase times blank

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/perf-tests#116]
Taking a look at [perf-dash](http://perf-dash.k8s.io/), I'm seeing that we're not generating any graphs for `TestPhaseTimer` metric even though we have the data available as JSON files in the job's artifacts.

For e.g consider graph `gce-100Nodes-master-DensityTestPhaseTimer` which is empty. But from a run of the job, I find the data available:

- https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/12924/artifacts/TestPhaseTimer_density_2018-04-23T18:14:50Z.json
- https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/12924/artifacts/TestPhaseTimer_load_2018-04-23T18:05:23Z.json

/assign @krzysied 
Krzysiek - Could you PTAL into this when you find time? This metric is useful sometimes to spot performance regressions.

cc @kubernetes/sig-scalability-bugs @wojtek-t

**Comment by krzysied** [comment]
Fixed in https://github.com/kubernetes/perf-tests/pull/117
