### ISSUE TITLE
perf-test should pass golint checks without -min_confidence=0.9

### ISSUE THREAD

**Issue by oxddr** [kubernetes/perf-tests#1163]
There is a number of `golint` violations across perf-tests repo. They are hidden as of now, because we pass `-min_confidence=0.9` to `golint`. We should:

1. Fix hidden issues (they should be self-explanatory) or if that's not feasible disable linter with an explanation (least prefered).
2. Remove `-min_confidence` from verify-golint.sh

/help-wanted
/good-first-issue

**Comment by qckzr** [comment]
@oxddr could you close this?, I already fixed it in #1203.

Thanks!

**Comment by oxddr** [comment]
/close

Thanks for your contributions!
