### ISSUE TITLE
ClusterLoader enhancement: use existing namespaces in a test

### ISSUE THREAD

**Issue by yuanchen8911** [kubernetes/perf-tests#1169]
clusterloader automatically creates and manages namespaces, but we need to use existing namespaces in some testing scenarios. For example, an internal controller has to create a bunch of namespaces with quota limits first for any tests in our environment.  There might be other use cases for using pre-created namespaces too. 

We have implemented an enhancement to clusterloader in support of using existing namespaces by adding a new keyword "_namespacesPrefix_" in the testconfig file.  The naming of namespaces must still follow the convention [prefix-]-1, -2, 3.... and managed by clusterloader. If a prefix of namespaces is defined and the corresponding namespaces have been created, clusterloader will skip the namespace creation. Would it be a useful feature?  If it is, we would like to submit a PR. 

Thanks for your feedback!

**Comment by wojtek-t** [comment]
At the high level I agree it would be useful. The case with "prepared namespaces" is definitely a valid one. Another usecase that I see is actually running multiple tests against the same set of namespaces.

So yes - I'm will to accept the feature at the high level.

If we get to details, I would like to avoid introducing a dedicated field for that.
Instead, I think that we should:
- deprecate the existing AutomanagedNamespaces field:
https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/api/types.go#L45
 [we've never figured out versioning policy, but we shouldn't delete immediately for sure, at least to let us update all the tests - @mm4tt ]
- introduce a struct to define namespaces; I need to think more about it, but the first attempt would be something like:

```
type NamespacesConfig struct {
  // optional, if set CL will use it instead its own 
  Prefix string
  // whether to adopt existing namespaces if they exist
  Adopt bool
[the reason I would like to make it explicit is to ensure that someone won't mess up something inconcsciously - if Adopt will be set to false (default), existing namespaces will result in error and should stop the test]
  // Number of namespaces that should exist after creation phase.
  Number int32
}
```

As mentioned above, we may want to tune/change that, but that's my first attempt.

Apart from that, the feature makes sense to me.

**Comment by yuanchen8911** [comment]
@wojtek-t Yes, the introduction of a namespace structure is certainly a better way.  So the logic would look like.

1.  Check whether the namespaces with names $Prefix-1, -2, -3, ...  exist.

2.  If the namespaces exist,  report an error and stop the test if _Adopt_ is not set  or use the existing namespaces if _Adopt_ is set.  Otherwise,  create the namespaces.

 A subtle issue is when _Number_ is greater than the number of preexisting namespaces (assuming _Adopt_ is set), should we create additional namespaces or report an error? For example,  if we have _"test": Prefix_,   _5: Number_,  test-1 and test-2 were created, should we create test-3, test-4 and test-5 or stop the test with an error?  The latter looks a more decent solution to me.

**Comment by wojtek-t** [comment]
I don't have strong preference - I would create those additional one, but the error also sounds fine to me.

**Comment by yuanchen8911** [comment]
Maybe a warning?

**Comment by wojtek-t** [comment]
Warning in logs? Noone will see that (technically it will be equal to not doing anything imho - so it's effectively the "create additiona" option).
Anyway - as I said, I don't have strong preference here.

**Comment by yuanchen8911** [comment]
Also, how about separating kubernetes cluster related configurations (e.g., kubeconfig, master-ip) from test specific parameters such as the number of namespaces, whether to delete stale namespaces, etc?  The former are still the command line options and the latter are defined in the testconfig yaml file.  

We can define the following structure for namespace.
```
// NamespaceConfig defines namespace parameters.
type NamespaceConfig struct {
        Number int32  `json: number` 
        NamePrefix string  `json: namePrefix`
        EnableExistingNamespaces  bool  `json: enableExistingNamespaces`
        DeleteStaleNamespaces bool `json.deleteStaleNamespaces`
        DeleteAutomanagedNamespaces bool `json.deleteAutomanagedNamespaces`
}
```
The corresponding configuration in the testconfig file looks like.
```
namespace:
   number: 1
   namePrefix: test
   EnableExistingNamespaces: true
   DeleteStaleNamespaces: false
   DeleteAutomanagedNamespaces: false
```
   @wojtek-t  any comments?

**Comment by wojtek-t** [comment]
Seems reasonable

**Comment by yuanchen8911** [comment]
Submitted a PR https://github.com/kubernetes/perf-tests/pull/1173

**Comment by yuanchen8911** [comment]
Two PRs were merged. 
 kubernetes/perf-tests#1181
 kubernetes/perf-tests#1173
