### ISSUE TITLE
consider checking labels to decide if it's a master node

### ISSUE THREAD

**Issue by xial-thu** [kubernetes/perf-tests#1191]
/area clusterloader

Now clusterloader2 just checks the suffix, however, in some costumed installation, node names don't contain a specific 'master'. Instead, it may contain labels such as `node-role.kubernetes.io/master=''`. Do we consider checking labels of nodes?

**Comment by wojtek-t** [comment]
We need to check if all existing tests set those label before we remove the current check. But we can immediately add it as an additional check (i.e. either name or label is set).

**Comment by xial-thu** [comment]
I'm using release 1.15 branch, relative code uses `IsMasterNode()` in vendor/k8s.io/kubernetes/pkg/util/system/system_utils.go

```go
// TODO: find a better way of figuring out if given node is a registered master.
// IsMasterNode checks if it's a master node, see http://gitlab.bj.sensetime.com/xialei1/perf-tests/issues/4
func IsMasterNode(node corev1.Node) bool {
	// We are trying to capture "master(-...)?$" regexp.
	// However, using regexp.MatchString() results even in more than 35%
	// of all space allocations in ControllerManager spent in this function.
	// That's why we are trying to be a bit smarter.
	name := node.Name
	if strings.HasSuffix(name, "master") {
		return true
	}
	return false
}
```

All the code in cl2 calls `system.IsMasterNode()`.

I personally think it's better to check labels, but it requires following changes:
1. `IsMasterNode` accepts `corev1.Node` as input, no longer `string`, so we gotta code it in maybe some 'util' pkg
2. since `corev1.Node` is the input, in pkg/measurement/util/gatherers/container\_resource\_gatherer.go line 115, we have to do another `nodes, err := c.CoreV1().Nodes().List(metav1.ListOptions{})` at first. Then the function checks pod's nodeName and calls `system.IsMasterNode(pod.Spec.NodeName)`. So we have to build a mapper, for example, `map[string]bool` to check if pod's nodeName is a master node.
3. It requires additional changes in vendor. See vendor/k8s.io/kubernetes/test/e2e/framework/metrics/metrics_grabber.go line 68. If we use go module instead, we have to copy that pkg. That seems not a good idea.

I would suggest the function to be 

```go
const (
	masterLabel = "node-role.kubernetes.io/master"
)

// TODO: find a better way of figuring out if given node is a registered master.
func IsMasterNode(node corev1.Node) bool {
	// We are trying to capture "master(-...)?$" regexp.
	// However, using regexp.MatchString() results even in more than 35%
	// of all space allocations in ControllerManager spent in this function.
	// That's why we are trying to be a bit smarter.
	name := node.Name
	if strings.HasSuffix(name, "master") {
		return true
	}

	// 'node-role.kubernetes.io/master' may be used by tools, such as kubeadm, to indicate which is the master node
	for k, _ := range node.GetLabels() {
		if k == masterLabel {
			return true
		}
	}

	return false
}
```

It causes some vendor problems by introducing this tiny improvement, so I'm not sure if it deserves.

Anyway I'm willing to contribute ^_^

**Comment by wojtek-t** [comment]
We stopped vendoring that function (and copied it) in master branch. So if you're willing to fix that in master branch, it would be great.

**Comment by xial-thu** [comment]
I checked that function in master branch, it says

>// This code will not be allowed to update to use the node-role label, since
>// node-roles may not be used for feature enablement.

So should I fix this or just leave it alone?

**Comment by wojtek-t** [comment]
This is fine, as we're going to use it only as an additional signal (at least for now). So if it's unset, we will return false anyway (no matter if you add this code or not).
Please go ahead and update.
