### ISSUE TITLE
Run shellcheck as a presubmit

### ISSUE THREAD

**Issue by oxddr** [kubernetes/perf-tests#1243]
There is significant amount of Bash in this repository. It'd be good to run shellcheck (in a form of a presubmit) to prevent some common issues. 

/assign

**Comment by kushthedude** [comment]
Hey, @oxddr I would like to work on this, can you give me more context do we need this as a pre-commit hook or a ci job?

**Comment by mm4tt** [comment]
/remove-lifecycle stale

@kushthedude, so sorry for the delayed answer. @oxddr left the team.

It should be a CI job. See an example of a [presubmit job](https://github.com/kubernetes/test-infra/blob/ede8f30c742abf701b3b94621b4402fcd578e6af/config/jobs/kubernetes/sig-scalability/sig-scalability-presubmit-jobs.yaml#L662) that calls `make verify-lint` in the perf-repo defined [here](https://github.com/kubernetes/perf-tests/blob/056bb5c113f52b0dd6172812ee9ab0550945223a/Makefile#L54)
