### ISSUE TITLE
Logic for measuring pod startup latency should be unified

### ISSUE THREAD

**Issue by oxddr** [kubernetes/perf-tests#1245]
Currently there is similar logic implemented in two places: `clusterloader2` and `slo-monitor`. Both tools measure the same thing. I can imagine this logic to be either extracted to a shared library (IMO preferred) or make one tool depend on the another. 

/area clusterloader
/area slo

**Comment by wojtek-t** [comment]
/remove-lifecycle stale

In addition, we should fix the logic so that it matches the SLI/SLO definition:
https://github.com/kubernetes/community/blob/master/sig-scalability/slos/pod_startup_latency.md
