### ISSUE TITLE
divideFloat zero got unmarshaling JSON problem

### ISSUE THREAD

**Issue by nicktming** [kubernetes/perf-tests#1272]
I noticed this issue is resolved in [#887](https://github.com/kubernetes/perf-tests/issues/887)

But this problem is still in the release-1.13 branch, since i am using k8s version 1.13.
should every k8s version use the master CL2 release or the corresponding version(k8s 1.13 uses CL2 release-1.13) ? and did perf-tests release branch keep consistent with k8s release branch ?

thx

**Comment by wojtek-t** [comment]
In general, you should be using branch corresponding to your k8s cluster.

That said, we started branching the repo relatively recently and the old branches aren't in the ideal shape. Over time, we should be getting to much better shape.

**Comment by nicktming** [comment]
thx
