### ISSUE TITLE
perfdash githubConfigDir err

### ISSUE THREAD

**Issue by liu4480** [kubernetes/perf-tests#1273]
I ran perfdash:2.23 in the pod, it got following errors
./perfdash \                                                                                 
                --www \
                --address=0.0.0.0:8080 \
                --builds=20 \
                --force-builds \
                --githubConfigDir=https://api.github.com/repos/kubernetes/test-infra/contents/config/jobs/kubernetes/sig-scalability \
                --githubConfigDir=https://api.github.com/repos/kubernetes/test-infra/contents/config/jobs/kubernetes/sig-release/release-branch-jobs

I0526 11:07:33.833095    1843 perfdash.go:62] Starting perfdash...
I0526 11:07:33.833708    1843 perfdash.go:112] Starting server...
I0526 11:07:33.833727    1843 perfdash.go:100] Fetching new data...
I0526 11:07:33.833792    1843 github-configs-fetcher.go:61] Downloading github spec from https://api.github.com/repos/kubernetes/test-infra/contents/config/jobs/kubernetes/sig-scalability
  line 1: cannot unmarshal !!map into []main.githubDirContent
E0526 11:07:35.341689    1843 perfdash.go:103] Error fetching data: yaml: unmarshal errors:
  line 1: cannot unmarshal !!map into []main.githubDirContent
I0526 11:07:45.343297    1843 perfdash.go:100] Fetching new data...
I0526 11:07:45.343316    1843 github-configs-fetcher.go:61] Downloading github spec from https://api.github.com/repos/kubernetes/test-infra/contents/config/jobs/kubernetes/sig-scalability
  line 1: cannot unmarshal !!map into []main.githubDirContent
E0526 11:07:46.705209    1843 perfdash.go:103] Error fetching data: yaml: unmarshal errors:
  line 1: cannot unmarshal !!map into []main.githubDirContent

then I tried to visit the url https://api.github.com/repos/kubernetes/test-infra/contents/config/jobs/kubernetes/sig-scalability, and I got :
{"message":"API rate limit exceeded for 103.220.76.84. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}

**Comment by liu4480** [comment]
So I 've two questions about perfdash:
1、could perfdash diaplay local clusterloader test?if can, how could perfdash got the test result from the case?
2、What Can I do to get the config files?

**Comment by mm4tt** [comment]
1. Technically you could, but it's not officially supported nor documented anywhere. Perfdash is a tool for displaying results from CI tests, it's not really meant to display local results
2. Given that it's second time someone got this error, could you please change this line - https://github.com/kubernetes/perf-tests/blob/5d15f0f796e371284b47a1831a5d06b73afb6bc4/perfdash/github-configs-fetcher.go#L73 and create a more descriptive error when the issue occurs? Please include the response body in the error message

**Comment by mirahmed753** [comment]
Setting a Github Token solved this issue for me which makes me think it's related to rate limiting from the github API. There's a PR that deals with this on #1374

**Comment by mm4tt** [comment]
/reopen
/good-first-issue

I'd like to see the error message changed before we close this one. It's to make sure it doesn't happen again and we waste time on debugging.

**Comment by Jeffwan** [comment]
/assign

I will take this one and file a PR soon

**Comment by mm4tt** [comment]
Thanks!
