### ISSUE TITLE
Perf-dash api-call-latency graphs seems to be broken for master jobs

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/perf-tests#1285]
Example graph - 
![TQOLneKPd3W](https://user-images.githubusercontent.com/2604887/83141123-6deb8180-a0ef-11ea-8541-19a1eefa7a05.png)

It looks similar for other resource/ver pairs

Other graphs (e.g. scheduler latency) look good

**Comment by mborsz** [comment]
Link: http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=APIServer&metricname=DensityResponsiveness_Prometheus&Resource=pods&Scope=namespace&Subresource=&Verb=LIST&SlowCount=0

Sample zereoed test: 

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1265689704909508608/artifacts/APIResponsivenessPrometheus_density_2020-05-27T19:12:12Z.json

The nonzero value is there

**Comment by mborsz** [comment]
http://perf-dash.k8s.io/buildsdata?jobname=gce-5000Nodes&metriccategoryname=APIServer&metricname=DensityResponsiveness_Prometheus

Data is there:
```
"1265689704909508608":[{"data":{"Perc50":2250,"Perc90":2450,"Perc99":2495},"unit":"ms","labels":{"Resource":"pods","Scope":"namespace","SlowCount":"20","Subresource":"","Verb":"LIST"}}
```

**Comment by mborsz** [comment]
New field has been added: SlowCount and perf-dash adds breakdown by that field (you need to chose whether you want to see timeline for SlowCount = X or Y), e.g.:

http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=APIServer&metricname=DensityResponsiveness_Prometheus&Resource=pods&Scope=namespace&Subresource=&Verb=LIST&SlowCount=20

http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=APIServer&metricname=DensityResponsiveness_Prometheus&Resource=pods&Scope=namespace&Subresource=&Verb=LIST&SlowCount=0

**Comment by mborsz** [comment]
It works now:

http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=APIServer&metricname=DensityResponsiveness_Prometheus&Resource=pods&Scope=namespace&Subresource=&Verb=LIST
