### ISSUE TITLE
Mouse click on perf-dash graph stopped redirecting to test logs

### ISSUE THREAD

**Issue by mborsz** [kubernetes/perf-tests#1290]
e.g. here:

http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=APIServer&metricname=DensityResponsiveness_Prometheus&Resource=pods&Scope=namespace&Subresource=&Verb=LIST

Click on any point used to redirect to test run logs, right now it redirects to url like:

```
http://perf-dash.k8s.io/undefined/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1242859244403822597/
```
/assign

**Comment by mborsz** [comment]
Relevant JS code:

https://github.com/kubernetes/perf-tests/blob/e7cea23c4f6b2a00b020c4bee36dd7c8c5983055/perfdash/www/script.js#L46-L52

and

https://github.com/kubernetes/perf-tests/blob/5d15f0f796e371284b47a1831a5d06b73afb6bc4/perfdash/perfdash.go#L121-L131

For some reason JS expects `storageUrl` while API returns `storageURL`.

**Comment by mborsz** [comment]
https://github.com/kubernetes/perf-tests/commit/5d15f0f796e371284b47a1831a5d06b73afb6bc4#diff-824455981b31a867d75ca77e17833a13L43 changes this

**Comment by mborsz** [comment]
https://github.com/kubernetes/perf-tests/pull/1291 fixes this

**Comment by mm4tt** [comment]
This has been fixed, we can close the issue

/close
