### ISSUE TITLE
negative value found for throughput metrics

### ISSUE THREAD

**Issue by chendave** [kubernetes/perf-tests#1307]
run "node-throughput" clusterloader test, and the metric of "schedule_to_run“ got negative values in the report,  

for example (I consistently saw this on ARM64), 

```json
    {
      "data": {
        "Perc50": -552.535002,
        "Perc90": -108.250499,
        "Perc99": 0.028548
      },
      "unit": "ms",
      "labels": {
        "Metric": "schedule_to_run"
      }
```

Debug into the source, the latency is truly a negative value, 
```bash
# pkg/measurement/util/phase_latency.go:88
(dlv) p lag
[]k8s.io/perf-tests/clusterloader2/pkg/measurement/util.LatencyData len: 100, cap: 100, [
        k8s.io/perf-tests/clusterloader2/pkg/measurement/util.latencyData {
                key: "test-02yq62-65/latency-pod-rc-0-4npgz",
                latency: -986631104,},
        k8s.io/perf-tests/clusterloader2/pkg/measurement/util.latencyData {
                key: "test-02yq62-18/latency-pod-rc-0-fd55x",
                latency: -975815380,},
        k8s.io/perf-tests/clusterloader2/pkg/measurement/util.latencyData {
                key: "test-02yq62-41/latency-pod-rc-0-hbv7t",
                latency: -975367453,},
        k8s.io/perf-tests/clusterloader2/pkg/measurement/util.latencyData {
                key: "test-02yq62-28/latency-pod-rc-0-b8nsc",
                latency: -974567117,},
```

and this is the time got for the pod,

```bash
(dlv) p o.times["test-02yq62-65/latency-pod-rc-0-4npgz"]["schedule"]
time.Time {
        wall: 986631104,
        ext: 63726771477,

(dlv) p o.times["test-02yq62-65/latency-pod-rc-0-4npgz"]["run"]
time.Time {
        wall: 0,
        ext: 63726771477,
        loc: *time.Location {
```

negative value for the schedule latency does not make sense to me, pls note, this is consistently found on ARM64 platform,  while it's zero on AMD64 platform.

AMD64:
```json
    {
      "data": {
        "Perc50": 0,
        "Perc90": 0,
        "Perc99": 0
      },
      "unit": "ms",
      "labels": {
        "Metric": "schedule_to_run"
      }
    }
```

**Comment by chendave** [comment]
/assign

I am currently investigate this issue.

**Comment by chendave** [comment]
/cc @mm4tt @wojtek-t @oxddr 

Do you have any comment, is that a known issue?

**Comment by mm4tt** [comment]
I haven't seen anything like that. Can it be caused by the clock skew? The `schedule to run` is computed as a difference between "pod started time", reported by kubelet on a "user" node inside the pod object and the "pod scheduled" event generated by scheduler on the master node. If there is a clock skew between master and node then a negative `schedule to run` is possible.

**Comment by chendave** [comment]
@mm4tt , it's not caused by clock skew, all the nodes are in the same timezone and synced well.

**Comment by mm4tt** [comment]
Could you reproduce and paste here:
1. Json/yaml of an affected pod
2. Scheduler event for "pod scheduled" for this pod, here is the code in cl2 that fetches it - https://github.com/mm4tt/perf-tests/blob/7db196a328d0483f5dbc293997e422f177e4be2d/clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go#L179, you can do it via kubetctl

**Comment by chendave** [comment]
I print out all those time in a readable format, take some of them as an example, pls note these time is not from the same pod, but enough to see the where is the issue.
``` bash
watch: 2020-06-04 18:11:31.28337351 +0800 CST m=+14.216775132
schedule: 2020-06-04 16:58:55.849727556 +0800 CST
run: 2020-06-04 16:58:55 +0800 CST
create: 2020-06-04 18:11:55 +0800 CST
```
You can see both "run" and "create" miss the parts of microsecond and nanosecond, when it comes to the calculation, `schedule_to_run` will lead to 
```2020-06-04 16:58:55 +0800 CST - 2020-06-04 16:58:55.849727556 +0800 CST```

so that we will get  a negative value here.

debug in the source, the `wall` field for "run" and "create" is empty, while "schedule" and "watch" is not, 

```
(dlv) p o.times["test-02yq62-65/latency-pod-rc-0-4npgz"]["schedule"]
time.Time {
        wall: 986631104,
        ext: 63726771477,

(dlv) p o.times["test-02yq62-65/latency-pod-rc-0-4npgz"]["run"]
time.Time {
        wall: 0,
        ext: 63726771477,
        loc: *time.Location {
```

Get the event show the similar result, 

```
//schedule
kubectl get event -o yaml | grep eventTime
...
eventTime: "2020-06-05T06:44:13.236091Z" 
...
```

//create
pod's creationTimestamp is: "2020-05-26T09:04:13Z"


so, the problem might be caused by how the pod's create and run timestamp is set, I am still investigating into the source, it's would be great if you could share with me the code link on how those timestamp is set.


thank you Matt!

**Comment by chendave** [comment]
> Could you reproduce and paste here:
> 
> 1. Json/yaml of an affected pod
> 2. Scheduler event for "pod scheduled" for this pod, here is the code in cl2 that fetches it - https://github.com/mm4tt/perf-tests/blob/7db196a328d0483f5dbc293997e422f177e4be2d/clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go#L179, you can do it via kubetctl

I think all the pod has the issues,  one for example,
```yaml
# kubectl get pod latency-pod-rc-0-tbltz -o yaml -n test-fn0frd-1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-06-05T11:00:23Z"
  generateName: latency-pod-rc-0-
  labels:
    group: latency
    name: latency-pod-rc-0
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
        f:labels:
          .: {}
          f:group: {}
          f:name: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"7f6eec88-be7a-45dc-a098-04d3e43087c2"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:automountServiceAccountToken: {}
        f:containers:
          k:{"name":"latency-pod-rc-0"}:
            .: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:terminationGracePeriodSeconds: {}
        f:tolerations: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-06-05T11:00:23Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"192.168.192.168"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubemark
    operation: Update
    time: "2020-06-05T11:00:24Z"
  name: latency-pod-rc-0-tbltz
  namespace: test-fn0frd-1
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: latency-pod-rc-0
    uid: 7f6eec88-be7a-45dc-a098-04d3e43087c2
  resourceVersion: "3490368"
  selfLink: /api/v1/namespaces/test-fn0frd-1/pods/latency-pod-rc-0-tbltz
  uid: 4ee30d96-56d1-4072-a0c9-6bb8fa3678ec
spec:
  automountServiceAccountToken: false
  containers:
  - image: k8s.gcr.io/pause:3.1
    imagePullPolicy: IfNotPresent
    name: latency-pod-rc-0
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: hollow-node-ff29x
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 900
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 900
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-06-05T11:00:23Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-06-05T11:00:24Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-06-05T11:00:24Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-06-05T11:00:23Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: fakeRuntime://latency-pod-rc-0-tbltz_test-fn0frd-1_4ee30d96-56d1-4072-a0c9-6bb8fa3678ec_0_latency-pod-rc-0_0
    image: k8s.gcr.io/pause:3.1
    imageID: k8s.gcr.io/pause:3.1
    lastState: {}
    name: latency-pod-rc-0
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-06-05T11:00:23Z"
  hostIP: 10.244.181.60
  phase: Running
  podIP: 192.168.192.168
  podIPs:
  - ip: 192.168.192.168
  qosClass: BestEffort
  startTime: "2020-06-05T11:00:23Z"
```

**Comment by chendave** [comment]
see: 
https://github.com/kubernetes/kubernetes/issues/15262
https://github.com/kubernetes/kubernetes/pull/15263/

and the code here,

https://github.com/kubernetes/kubernetes/blob/22de8fc321386277565aabc35dfc45bf371a7be7/pkg/kubelet/status/status_manager.go#L668-L675

**Comment by chendave** [comment]
this is done purposely, we need to consider to workaround the issue, at least make it not a negative value.

**Comment by chendave** [comment]
@mm4tt

**Comment by chendave** [comment]
Do we have any other way to get the the finer granularity timestamp with nanosecond? this currently impact the time of "create" and "run".

**Comment by mm4tt** [comment]
Just to confirm, it has been like that for some time, it's nothing new, right?
If so, then I think the only thing we can do is to change clusterloader2 code to export 0 if a computed value is negative. Could you send a PR to do that?
Unfortunately, I don't know of any way to get finer timestamps. I'm aware that the method of calculating pod startup latency is subject to an error, but given that pod startup latency is usually in O(a few seconds) the <1s (rounding up) error is acceptable.

**Comment by chendave** [comment]
> Just to confirm, it has been like that for some time, it's nothing new, right?

yes, and I think it's not easy to convince apiserver and kubelet to change the current code logic to solve the issue like this.
> If so, then I think the only thing we can do is to change clusterloader2 code to export 0 if a computed value is negative. Could you send a PR to do that?
> Unfortunately, I don't know of any way to get finer timestamps. I'm aware that the method of calculating pod startup latency is subject to an error, but given that pod startup latency is usually in O(a few seconds) the <1s (rounding up) error is acceptable.

In my testing, more than 90% pods are affected, I tend to agree with you on this since I don't have a better way to fix it, will push a PR soon and cc you then.

**Comment by chendave** [comment]
Btw, I don't know exactly the reason, this happened in my testing on X86, `EventTime` maybe null and clusterloader2 will get fetch `firstTimestamp`, which don't have nanosecond as well, so the "schedule_to_run" will get all the result with "0" since both the "schedule" and "run" has discarded the precision which is less than second.

```yaml
  eventTime: null
  firstTimestamp: "2020-06-08T09:25:34Z"
```

and as a comparsion
```yaml
  eventTime: "2020-06-08T09:24:23.244682Z"
  firstTimestamp: null
```

```golang
	for _, event := range schedEvents.Items {
		key := createMetaNamespaceKey(event.InvolvedObject.Namespace, event.InvolvedObject.Name)
		if _, exists := p.podStartupEntries.Get(key, createPhase); exists {
			if !event.EventTime.IsZero() {
				p.podStartupEntries.Set(key, schedulePhase, event.EventTime.Time)
			} else {
				p.podStartupEntries.Set(key, schedulePhase, event.FirstTimestamp.Time)
			}
		}
	}
```

**Comment by chendave** [comment]
this is what I get on X86, 
```yaml
    {
      "data": {
        "Perc50": 0,
        "Perc90": 0,
        "Perc99": 0
      },
      "unit": "ms",
      "labels": {
        "Metric": "schedule_to_run"
      }
    }
```

with the suggested change, I feel likely the result will be looks like this on my ARM64 as well.

**Comment by wojtek-t** [comment]
It's probably a matter of what k8s release we're using.

The FirstTimestamp is set using the old events API, the EventTime is used when using new Events API. Scheduler switched to use the new one IIRC in 1.16.
