### ISSUE TITLE
Take perf-dash to v1.0

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/perf-tests#137]
We've made several improvements to [perf-dash](http://perf-dash.k8s.io/) in the past few months (thanks a lot @krzysied for the work!). I think it's time to make some final improvements and cut the first major release (1.0). Mainly, let's make using it easier (even for non-scalability folks - for e.g release team has been asking for it). Some work-items that come to my mind:

- Split the graphs based on job-name first (i.e gce-100, kubemark-500, etc) and then metric (i.e ApiserverResponsiveness, SchedulerMetrics, etc) so that navigation is easier
- Add units to the axes in the graphs (otherwise the graphs aren't understandable)
- Load individual graphs on demand rather than pre-loading everything at start (so we don't wait for tens of seconds before we can see anything)
- sth else?

/assign @krzysied 
cc @kubernetes/sig-scalability-misc @wojtek-t

**Comment by krzysied** [comment]
What a coincident... #138

**Comment by krzysied** [comment]
> Add units to the axes in the graphs (otherwise the graphs aren't understandable)

I've looked into this. The units are implemented, but there is a typo in https://github.com/kubernetes/perf-tests/blob/7881ce52d23d547e813e2ac6b6aa8870525e11c3/perfdash/www/script.js#L81 
I will add fix after #138 is merged.

**Comment by krzysied** [comment]
With #149 being icing on the cake, I think we are ready to make 1.0 release.
@shyamjvs  Is there anything that should be added before making it 1.0?

**Comment by shyamjvs** [comment]
Yes, it looks great - waaay better than before. Thanks @krzysied!
Could you make one final change of adding "Runs over time" label to the x-axis in the graphs? We can bump it to 1.0 after that.

**Comment by shyamjvs** [comment]
Closing this with the final change merged. Thanks!
/close
