### ISSUE TITLE
Should they use RWMutex?

### ISSUE THREAD

**Issue by dddddai** [kubernetes/perf-tests#1395]
Should they use RWMutex instead of Mutex to avoid the contention between readings?

https://github.com/kubernetes/perf-tests/blob/95e5a1ca466ca871b2b9f7b7fb43309273f8933b/clusterloader2/pkg/measurement/util/phase_latency.go#L63-L85

https://github.com/kubernetes/perf-tests/blob/9790f58705ddfac0225ee18e07eca7d66475d2e1/clusterloader2/pkg/errors/error_list.go#L37-L42

https://github.com/kubernetes/perf-tests/blob/9790f58705ddfac0225ee18e07eca7d66475d2e1/clusterloader2/pkg/errors/error_list.go#L61-L75

If it's necessary, I am willing to contribute.

**Comment by wojtek-t** [comment]
RWMutex makes sense in places where there are many more reads than writes.
In all places above, we don't really suffer from contention, so changing it doesn't make much sense (given RWMutex is a bit more expensive than regular Mutex).

In general - we shouldn't be changing those unless there is clear reason for it confirmed with a real-life benchmark. It's not the case here.
