### ISSUE TITLE
Avoid provider specific logics out of provider package

### ISSUE THREAD

**Issue by Catramen** [kubernetes/perf-tests#1399]
PR  #1344 is trying to consolidate all the provider related code into one packge.

The goal is to make it easy to develop new providers and easy to develop new features for existing providers.

We should avoid these:
if config.CloudProvider != "kubemark" 
InKubemark:                        strings.ToLower(provider.Name()) == "kubemark",

And prefer this:
if provider. Features().SupportXXXX {
}

**Comment by wojtek-t** [comment]
This has been addressed in the meantime. We can file a more dedicated issues for specific changes if needed in the future.
