### ISSUE TITLE
[clusterloader2] [monitoring] The grafana dashboards should have the "nullPointMode" set to "null" instead of connected 

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/perf-tests#1410]
Currently, all pre-configured grafana dashboards use the default value of the `nullPointMode` setting, which is `connected`. Connected is not a good choice, sometimes it's very misleading and hides critical moments when api-server was not available. We should use the `null` setting instead.

1. The dashboards are located in https://github.com/kubernetes/perf-tests/tree/master/clusterloader2/pkg/prometheus/manifests/dashboards
2. An example line that should be changed - https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json#L54
3. NOTE: json files shouldn't be edited manually, we need to change the python code to start setting `nullPointMode` to `null` 

/good-first-issue
/help-wanted

**Comment by Evalle** [comment]
Hey @mm4tt I can take care of it. 
/assign

**Comment by Evalle** [comment]
Got sidetracked by other stuff, feel free to assign this issue. 
/unassign

**Comment by mm4tt** [comment]
Done in https://github.com/kubernetes/perf-tests/pull/1415

/close
