### ISSUE TITLE
perf-dash: remove average from graphs when the data doesn't have averages

### ISSUE THREAD

**Issue by adtac** [kubernetes/perf-tests#1438]
http://perf-dash.k8s.io/#/?jobname=kubemark-100Nodes&metriccategoryname=Scheduler&metricname=SchedulingThroughput

![Screenshot_2020-08-27 Screenshot](https://user-images.githubusercontent.com/7521600/91472163-116e3e80-e865-11ea-9605-033a29aaa790.png)

**Comment by mm4tt** [comment]
It's not 0, we just stopped exporting it in https://github.com/kubernetes/perf-tests/pull/1093 as it was pointless (it didn't really work)

The only thing to do is to remove the "Avg" from perf-dash as it's not exported anymore by CL2

**Comment by wojtek-t** [comment]
@adtac @mm4tt - hasn't this been addressed in the meantime?

**Comment by adtac** [comment]
@wojtek-t I'm not aware of a fix, the average data point is still being shown in perf-dash. I'll edit the title to reflect the issue more accurately.

**Comment by adtac** [comment]
Unassigning myself as I don't think I'll realistically be able to work on this in the near future.

/unassign
