### ISSUE TITLE
Migrate dns benchmarks to python3

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/perf-tests#1458]
Python2 has been deprecated, yet we still use it in some of our benchmarks.
In https://github.com/kubernetes/perf-tests/pull/1457, we needed to pin python/pip version to python2/pip2 to fix failing tests.
As a follow up we should migrate those tests to use python3. 

/kind cleanup
/good-first-issue

**Comment by vamossagar12** [comment]
hey @mm4tt I can take it up.. I have started working on https://github.com/kubernetes/perf-tests/issues/787#issuecomment-671210865 which is related to SLIs which looks at DNS related benchmarks. Do you think they are related?

**Comment by wojtek-t** [comment]
They are not related at all.

**Comment by vamossagar12** [comment]
Oh ok :) either ways, if there aren't any takers, i can take it up.

**Comment by mm4tt** [comment]
This is great, thanks!

**Comment by vamossagar12** [comment]
@mm4tt I think the issue is that while the pip install command installed numpy version numpy-1.19.1 which works exclusively on python 3, the python scripts are still running on python2. This is evident from the logs on the test that had failed:
```I0907 08:42:49.487] Installing collected packages: numpy
I0907 08:42:55.359] Successfully installed numpy-1.19.1
W0907 08:42:56.755] Traceback (most recent call last):
W0907 08:42:56.756]   File "py/run_perf.py", line 23, in <module>
W0907 08:42:56.756]     from runner import Runner
W0907 08:42:56.757]   File "/go/src/k8s.io/perf-tests/dns/py/runner.py", line 29, in <module>
W0907 08:42:56.757]     from data import Parser, ResultDb
W0907 08:42:56.757]   File "/go/src/k8s.io/perf-tests/dns/py/data.py", line 18, in <module>
W0907 08:42:56.757]     import numpy
W0907 08:42:56.757] ImportError: No module named numpy```

The reason for that could be the shebang line specified at the beginning of the python scripts which I think are pinning the scripts to python 2:

https://github.com/mm4tt/perf-tests/blob/master/dns/py/data.py#L1

If we just change it to use python3, we might get newer issues which is because of the syntactical differences between 2 and 3.

I can fix this, but one question on how to test it? Is it recommended to test just this one test once i make a code push? What command should I use for that?

**Comment by mm4tt** [comment]
This is the test we want to run - https://github.com/kubernetes/test-infra/blob/7bf5e377a57c206f4a06088988ba9eb86198c816/config/jobs/kubernetes/sig-scalability/sig-scalability-periodic-jobs.yaml#L466
Currently, it's run only continuously, there is no presubmit for it.

We should start with adding a presubmit test (basically copy-paste-edit the test into the presubmit-jobs.yaml file). Once we have it, you'll be able to switch to python3/pip3 and send a PR with the changes. As you wrote, most likely it will fail due to syntax differences, but we'll be able to detect/address that with the new presubmit.

**Comment by vamossagar12** [comment]
Thanks @mm4tt , when you say presumt-jobs.yaml, you mean this one here:
https://github.com/kubernetes/test-infra/blob/7bf5e377a57c206f4a06088988ba9eb86198c816/config/jobs/kubernetes/sig-scalability/sig-scalability-presubmit-jobs.yaml

So, I will need to send a pr to test-infra as well with this new test also configured?

**Comment by mm4tt** [comment]
Yes and yes :)

**Comment by vamossagar12** [comment]
@mm4tt created a pre submit job for kube dns. PR: https://github.com/kubernetes/test-infra/pull/19217

**Comment by vamossagar12** [comment]
Created another PR for actual migration from python2 to python3: https://github.com/kubernetes/perf-tests/pull/1470
Note that I haven't changed the shebang lines at the starting of the python files, just to see what kind of failures do we get.

**Comment by wojtek-t** [comment]
This has been fixed in the meantime. Closing.
