### ISSUE TITLE
Pod Start Latency Measure Accuracy Problem

### ISSUE THREAD

**Issue by weiling61** [kubernetes/perf-tests#1468]
When I test pod startup latency, I found that cluster loader uses "pod.CreationTimestamp.Time" as createPhase timestamp. 
Standard k8s api only returns Pod creationTimeStamp with a precision in second --- all nano second contents are set to 000000. My question is: without nano second content in timestamp, does Pod startup latency make any sense?

**Comment by wojtek-t** [comment]
>  My question is: without nano second content in timestamp, does Pod startup latency make any sense?

Is it accurate - it isn't.
Does it make sense - yes - it makes sense. The diference from real is <1s, which isn't perfect, but gives a strong signal.

/cc @mm4tt

**Comment by mm4tt** [comment]
Yeah, also see this - https://github.com/kubernetes/perf-tests/issues/1307

**Comment by weiling61** [comment]
Thanks @mm4tt and @wojtek-t for the pointers. The pod latency data has its limitation. But for now it seems nothing we can do at cluster loader side.
