### ISSUE TITLE
ClusterLoader2:  podStartupLatency may not correct

### ISSUE THREAD

**Issue by Dingshujie** [kubernetes/perf-tests#1487]
**What happened**:
now CL2 use pod binding eventTime as pod scheduled timestamp, and use pod container status startAt as pod running timestamp，see following two graph,  and we see that running time is early than schedule time, because of event time use metav1.MicroTime(use RFC3339Micro), and startAt use metav1.Time(use time.RFC3339), it influence performace test results. 

![image](https://user-images.githubusercontent.com/13744637/93884960-24feaf00-fd16-11ea-8e0c-028b391f19b7.png)

![image](https://user-images.githubusercontent.com/13744637/93885080-524b5d00-fd16-11ea-8640-1c516391a761.png)

@mborsz @mm4tt

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
use kubemark cluster, and run performance test
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by wojtek-t** [comment]
See: https://github.com/kubernetes/perf-tests/issues/1468
