### ISSUE TITLE
Don't run access-tokens test as part of presubmits

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/perf-tests#1489]
Access-tokens is really targeted test that didn't yet discover any problem.
While it's reasonable to leave it in continuous testing (at least for now), there is not much sense in running it as part of presubmit, as it slows down the presubmit (it's often the slowest presubmit in k/k).

@jprzychodzen @mborsz @tosi3k

**Comment by wojtek-t** [comment]
@mborsz @marseel - when you will be switching density+load test it might make sense to make it together (this would allow us to still run both density and load for the time of transition, at least at 100 scale without increasing time the whole test takes).

**Comment by jprzychodzen** [comment]
Numbers to get the context
 *  access tokens test (with running cluster) ~ 8 minutes.
 *  creating pods/tokens/service accounts (without pods ready) ~ 30 seconds
 *  waiting for pods to be ready ~ 1 minute

I remember that initially we wanted to include access tokens test into load test, to cover additional dimensions, after enough soak time.

If merged: 'Wait for controlled pods running' could be shared with a load test step.

So adding access-tokens test to load test will add only 30 seconds compared to the solution with disabled access-tokens. I do not see that as a huge cost especially that we are testing a [scalability dimension](https://github.com/kubernetes/community/blob/master/sig-scalability/configs-and-limits/thresholds.md).

Are we really this tight with presubmit time that we should try to optimize for those 30 seconds?

**Comment by mborsz** [comment]
@jprzychodzen , I think Wojtek is recommending removing access tokens completely from presubmit to save all ~10m it takes, not merging it into density test.

**Comment by jprzychodzen** [comment]
Yes, I was asking about removing vs merging.

**Comment by wojtek-t** [comment]
Yes - I'm saying:
- the test takes 8m
- it never caught any issue

So if we catch the problem in postubmit (which is running continuously anyway) - so ~1-2hours later it's good enough.
So I think there is no point in running it in presubmit.
