### ISSUE TITLE
should we reconsider how scheduling throughput is measured?

### ISSUE THREAD

**Issue by adtac** [kubernetes/perf-tests#1533]
Currently, the scheduling throughput is measured as follows. Every 5 seconds, the number of pods scheduled is measured. The previously measured number of scheduled pods is subtracted from this number and the difference is divided by 5 to get the average throughput for the 5 second period. This is repeated until **all pods are running** and at each 5 second interval, the average is appended to an array. The median, 90th, and 99th percentile of this array are reported.

I propose that we stop appending to the array as soon as the number of pods pending scheduling is zero. Waiting for all pods to be running is outside of the scheduler's control. During testing, I often run into situations where all pods are scheduled, but a large number of pods are still yet to achieve running status. This pointless appends zeros to the throughput measurements, skewing the median lower unnecessarily.

/sig scheduling
/cc @ahg-g @alculquicondor

**Comment by alculquicondor** [comment]
+1

Running phase is indeed independent of scheduled. Still, let's say in the last 5 seconds we only scheduled the remaining 5 pods. Then the throughput for that period is 1 pod/s, which doesn't mean that the scheduler couldn't handle more.

That said, your proposal moves the throughput calculation in the right direction.

**Comment by ahg-g** [comment]
>I propose that we stop appending to the array as soon as the number of pods pending scheduling is zero.

Sounds good to me.

> Still, let's say in the last 5 seconds we only scheduled the remaining 5 pods.

That is just one data point, in a long enough run it shouldn't have an impact on even the 99th percentile.

**Comment by wojtek-t** [comment]
Scheduling throughput has be rewritten completely to be metrics based:
https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/pkg/measurement/common/scheduling_throughput_prometheus.go

The measurement you're talking about isn't the right way of measuring it, because it may be affected by e.g. slow watch.
We will remove it completely in the next couple days. So please don't invest into it...
@marseel @mborsz - FYI

**Comment by ahg-g** [comment]
@wojtek-t out of curiosity what metric will be used? one exported by the apiserver?

**Comment by wojtek-t** [comment]
POST pods/bindings

**Comment by alculquicondor** [comment]
What is the current status of this effort @wojtek-t?

**Comment by wojtek-t** [comment]
It was more-or-less implemented:
https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/pkg/measurement/common/scheduling_throughput_prometheus.go

but there were some issues (which I forgot) to enable that. Someone will need to sit down and work on it (which we don't seem to have capacity now).
