### ISSUE TITLE
OOM tracker timing out in clusters with very large number of events

### ISSUE THREAD

**Issue by jkaniuk** [kubernetes/perf-tests#1536]
With > 500k events, OOM tracker have problems starting watching for events with narrow selector for OOMs
```
[measurement call TestMetrics - TestMetrics error: [
  action start failed for ClusterOOMsTracker measurement: 
    starting cluster OOMs measurement problem: 
      problem with OOM events informer starting: 
        timed out waiting for caches to sync]
```
As there are O(0) OOM events, initial list before watch start needs to process all events before returning the result. apiserver call times out, as apiserver tries retrieve results from etcd paginating over all events with default page size of 500 results.

**Comment by jkaniuk** [comment]
Ideas how to improve it:

slo-monitor faced similar challenges and ended with:
- moving reflector to custom NoStore Store implementation that drops all data as soon as possible
- limiting first list calls to 1 result as previous events were not so important

We do not need to worry about memory consumption so much, so let's not switch to NoStore right away.

Limiting list call to 1 is problematic:
1. listing OOMs that happened during test initialization have been helpful in the past
2. when no events matches our narrow selector, it would still go over all events

Addressing 1)
- we can issue separate list call before starting a watch to collect previous events
- this call could timeout
  - we can increase limit to 10k events per page
- even  with increased limit, that would be long running api call (could violate our SLOs)
  - we could remove selector to iterate over all events and filter them out in OOMTracker - that would change single API call into pagination over all events, which would reduce any single call latency

Addressing 2)
- we can similarly start watch without a selector and with limit 1 - that would issue a quick list call and watch over all events
   - all filtering would need to be done in OOMTracker

**Comment by jkaniuk** [comment]
/assign @tosi3k 

@wojtek-t 
@mborsz

**Comment by wojtek-t** [comment]
> we can similarly start watch without a selector and with limit 1 - that would issue a quick list call and watch over all events

We can not set filter for list, but set filter for watch. That means that OOMTracker won't need to do filtering at all.

**Comment by jkaniuk** [comment]
> > we can similarly start watch without a selector and with limit 1 - that would issue a quick list call and watch over all events
> 
> We can not set filter for list, but set filter for watch. That means that OOMTracker won't need to do filtering at all.

If we can issue initial list call for watch with limit 1 and without selector but open watch with selector then yes - we can do that.
I think that someone said that it is possible, if so, then this is the best way.

**Comment by tosi3k** [comment]
This is currently blocked by https://github.com/kubernetes/perf-tests/issues/1543. We can revisit this after we sort out the NPD issues first.

**Comment by tosi3k** [comment]
I created a candidate fixing PR some time ago but it was blocked on the (already fixed) bug in the OOM tracker dependency, node-problem-detector.

The PR requires testing but I didn't have time to come back to it yet (hopefully will have some more soon).

/remove-lifecycle stale
