### ISSUE TITLE
old (beta) topology labels are going away

### ISSUE THREAD

**Issue by thockin** [kubernetes/perf-tests#1554]
Hello.  

The labels `failure-domain.beta.kubernetes.io/zone` and `failure-domain.beta.kubernetes.io/region` have been deprecated for almost a year now and are scheduled to be removed from kubernetes/kubernetes after 1.20 (Q1'21).

In prep for that I scanned all our repos looking for places that reference the old names and not the new ones.  There are a couple such places in this repo.  Without knowing exactly what this codebase is doing, I can't say for sure if it is a problem or not, so I am just filing issues.

Please take a look and be advised of this upcoming change.

**Comment by wojtek-t** [comment]
Thanks Tim.

@mm4tt - please add that to the next iteration planning, it should be less than half an hour of work...

**Comment by mm4tt** [comment]
Done. Added to the top of our backlog

**Comment by wojtek-t** [comment]
Reopening - the PR is being reverted.

**Comment by wojtek-t** [comment]
@thockin - it seems that for GCE disks we're still setting only the old labels only (which we rely on here...)

**Comment by thockin** [comment]
Yeah, I am working with Storage folks - that logic has not yet been
converted to use the new labels. :(

@msau42

**Comment by msau42** [comment]
cc @mattcary

**Comment by tosi3k** [comment]
@msau42 @mattcary do we have an OSS issue to track the lack of new labels for the disks?

**Comment by msau42** [comment]
https://github.com/kubernetes/kubernetes/issues/92237

**Comment by Jiawei0227** [comment]
Hey folks, I am working on adding the GA labels to the GCE PD disk PV.
But I think currently the way that people getting information from PV labels can be a csi migration blocker. Since after we switch to PD CSI driver mode, the new PV does not have topology labels on it. @msau42 Do we want to consider adding the labels to the CSI created PV?

**Comment by msau42** [comment]
Yes, for informational purposes, I think we should set labels on the PV object (using the GA labels). For scheduling though, it only looks at the PV.NodeAffinity.

For native CSI volumes though, we would need to build an admission controller to label PV objects with the gke csi labels: https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/390
