### ISSUE TITLE
perf-dash: make time axis labels more readable

### ISSUE THREAD

**Issue by adtac** [kubernetes/perf-tests#1585]
**What would you like to be added**: Make the time axis labels in graphs more readable in the following ways:

1. We do not need every data point to have a label in the axis. Users can click on the data point to go to the prow link.
2. Use human-readable timestamps instead of what appears to be UNIX epoch.

**Why is this needed**: The time axis labels are currently unreadable. Here's an example :)

![Screenshot_2020-11-19 Screenshot](https://user-images.githubusercontent.com/7521600/99707158-127cc980-2a6a-11eb-9137-f578535d7810.png)

**Comment by wojtek-t** [comment]
I would like to get rid of perf-dash eventually and migrate to something more standard like Mako.
So if someone wants to pick it up it's great, but I don't we we will invest into it as a SIG.
