### ISSUE TITLE
imagepreload.go if timeout should return err

### ISSUE THREAD

**Issue by zhou1992513** [kubernetes/perf-tests#1597]
if err!=nil should return err 
	
klog.V(2).Infof("Waiting for %d Node objects to be updated...", clusterSize)
	if err := wait.Poll(pollingInterval, pollingTimeout, func() (bool, error) {
		klog.V(3).Infof("%d out of %d nodes have pulled images", len(doneNodes), clusterSize)
		return len(doneNodes) == clusterSize, nil
	}); err != nil {
		return nil

**Comment by wojtek-t** [comment]
https://github.com/kubernetes/perf-tests/blob/2bef79ff91a8e5b39976b5dbbfdafd0f5521211f/clusterloader2/pkg/imagepreload/imagepreload.go#L136
