### ISSUE TITLE
Migrate scalability jobs from bootstrap.py to pod-utils

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/perf-tests#1624]
We tried once but failed. One of the biggest blocker would be to make logexporter work in the pod-util world. See discussion in https://github.com/kubernetes/test-infra/pull/17215

**Comment by wojtek-t** [comment]
/remove-lifecycle stale

@mborsz - with the changes you were doing to logdumping - will it be possible to do now?

**Comment by mborsz** [comment]
I don't know that:
1. It's not enabled in OSS, yet.
2. I'm not sure if this was the only blocker

**Comment by tosi3k** [comment]
I was able to successfully migrate the `gce-cos-master-scalability-100` CI job to pod-utils.

As SIG Scalability takes care of bazillion different job configs, let's track the effort of migrating all other jobs per-file:
* [ ] [sig-scalability-adhoc.yaml](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-scalability/sig-scalability-adhoc.yaml)
* [ ] [sig-scalability-cleanup.yaml](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-scalability/sig-scalability-cleanup.yaml)
* [ ] [sig-scalability-experimental-periodic-jobs.yaml](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-scalability/sig-scalability-experimental-periodic-jobs.yaml)
* [ ] [sig-scalability-golang.yaml](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-scalability/sig-scalability-golang.yaml)
* [ ] [sig-scalability-periodic-jobs.yaml](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-scalability/sig-scalability-periodic-jobs.yaml)
* [ ] [sig-scalability-presubmit-jobs.yaml](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-scalability/sig-scalability-presubmit-jobs.yaml)
* [ ] [sig-scalability-release-blocking-jobs.yaml](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-scalability/sig-scalability-release-blocking-jobs.yaml)
* [ ] [1.20 jobs](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-release/release-branch-jobs/1.20.yaml)
* [ ] [1.19 jobs](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-release/release-branch-jobs/1.19.yaml)
* [ ] [1.18 jobs](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-release/release-branch-jobs/1.18.yaml)

**Comment by tosi3k** [comment]
Last remaining PRs to merge to close this issue:
* https://github.com/kubernetes/test-infra/pull/21350 (ad hoc job),
* https://github.com/kubernetes/test-infra/pull/21349 (presubmits),
* https://github.com/kubernetes/test-infra/pull/21352 (release branch jobs).

Let's wait until Monday and start with merging the ad hoc job (to see whether our approach to presubmit migration is right) as this is an optional presubmit job.

**Comment by tosi3k** [comment]
Done \o/.
