### ISSUE TITLE
Error while Prometheus Controller

### ISSUE THREAD

**Issue by CLFlemon** [kubernetes/perf-tests#1630]
When I use parameters 'enable-prometheus-server' and  '--tear-down-prometheus-server=false'.
Log error：Error while creating Prometheus Controller: multi client set creation error: config prepare failed: error loading kubeconfig: open /xxx/xxx
What should I do as a novice？

**Comment by mm4tt** [comment]
Does the kubeconfig exist at /xxx/xxx? CL2 needs a valid kubeconfig in order to connect to the cluster it tests

**Comment by CLFlemon** [comment]
I solved the problem.But the strange thing is, my parameter KUBE_ CONFIG has been set up, but the Prometheus server still automatically looks for my {$home} /. Kube / config. But thank you all the same.
