### ISSUE TITLE
HTTP perf-dash should redirect to HTTPS instead of returning 404

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/perf-tests#1646]
[Originally filed by @adtac in https://github.com/kubernetes/test-infra/issues/20359]

---

What happened: http://perf-dash.k8s.io returns 404.

What you expected to happen: It should redirect to https://perf-dash.k8s.io instead.

How to reproduce it (as minimally and precisely as possible): Go to http://perf-dash.k8s.io on your browser.

cc @mborsz

**Comment by mm4tt** [comment]
Maybe it was fixed in the meantime but it seems to be working both over http and https.
Also, redirect from http to https should happen in the LB config not in the perf-dash code. So if the issue persists, an issue should be filed against kubernetes/k8s.io to change the LB settings
