### ISSUE TITLE
Passing CL2_-prefixed env vars to object templates does not work 

### ISSUE THREAD

**Issue by tosi3k** [kubernetes/perf-tests#1691]
We have a couple of objects that intend to use `CL2_`-prefixed environment variables like in [statefulset.yaml](https://github.com/kubernetes/perf-tests/blob/c64f92e65884de524e938941135aac76fc629653/clusterloader2/testing/load/statefulset.yaml#L1,L2).

Overriding the default values does not work in that case, though, as if the objects do not have visibility into these env vars.

/kind bug

**Comment by mm4tt** [comment]
From a cursory look at the code I believe it should work.

1. CL2 envs are present in the mapping returned by config.GetMapping - https://github.com/kubernetes/perf-tests/blob/8e56c52b47a9d5b221ceec2c0445f49924bbef4f/clusterloader2/pkg/config/template_provider.go#L224
2. This mapping it's used to create the context - https://github.com/kubernetes/perf-tests/blob/58e7520edcae3b06c39336e39bf827af85019461/clusterloader2/pkg/test/test.go#L64
3. Mapping that we use to instantiate an object from template is a copy of the mapping from the context plus some extra values - https://github.com/kubernetes/perf-tests/blob/8c85b1d608511e76d8c8180b3bc6163b736e20ec/clusterloader2/pkg/test/simple_test_executor.go#L295

**Comment by tosi3k** [comment]
You're right, everything works as expected. It was my manual CL2 runs that have made me believe there was something wrong since instead of typing the following line in the shell:
```
export CL2_ENV_VAR=VALUE
```
I typed as follows:
```
CL2_ENV_VAR=VALUE
```
So the `CL2_ENV_VAR` was just set for the shell, not for all processes started from that shell...

/close
