### ISSUE TITLE
kind provider for CL2

### ISSUE THREAD

**Issue by lyzs90** [kubernetes/perf-tests#1693]
I got really close to running CL2 on a [kind](https://kind.sigs.k8s.io/) cluster with the local provider. The first issue I faced was having to wrap the poll eg. `docker exec -it <containerID> curl -X GET -k https://localhost:10259/metrics` during the metric collection. The second was because of unauthenticated access to the scheduler's metrics endpoint (somewhat related to https://github.com/kubernetes/kubernetes/issues/93748).

If we can get these out of the way, I'm wondering if we could consider supporting a kind provider. It would make it easy for anyone to start working on CL2

**Comment by mm4tt** [comment]
It'd be great even to have kind working without those features. If we need to disable them only for kind we can do that using the [provider](https://github.com/kubernetes/perf-tests/blob/fd7ccf5b51ae0b54e6c2152f54c3c51e56147c83/clusterloader2/pkg/provider/provider.go) interface. After that we can open an issues to make them work for kind and work on them independently

**Comment by lyzs90** [comment]
Closing as it was added in https://github.com/kubernetes/perf-tests/pull/1701.
