### ISSUE TITLE
Remove deprecated automanagedNamespaces

### ISSUE THREAD

**Issue by lyzs90** [kubernetes/perf-tests#1696]
AutomanagedNamespaces has been deprecated but is still being used in `node-throughput` and `windows-tests` configs. These configs are used in sig-scalability periodic jobs and sig-windows tests.

**Comment by mm4tt** [comment]
Thanks!

/good-first-issue
/help-wanted

**Comment by Palerion** [comment]
Hi!  I'm a new contributor, and I'd love to work on this as my first issue.  Thanks!

**Comment by lyzs90** [comment]
@Palerion Please go ahead :)

In https://github.com/kubernetes/perf-tests/pull/1694 I've marked the places where automanaged namespaces could be removed.

Based on what I observed on testgrid, these [jobs](https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubernetes) are still being run today:
- ci-kubernetes-e2e-gce-node-throughput
- ci-kubernetes-e2e-gce-node-containerd-throughput
- ci-kubernetes-e2e-windows-node-throughput
- ci-kubernetes-e2e-windows-node-throughput-iis

So we may want to port them over to the [Namespaces api](https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/api/types.go#L136).

**Comment by sgirem463** [comment]
@Palerion Not sure if you are actually working on this since I don't see this issue assigned. If not, I would like to pick it up.

**Comment by sgirem463** [comment]
@lyzs90 I am a new contributor, can I assign this to myself since it's not assigned.

**Comment by sgirem463** [comment]
@lyzs90 I have located:

ci-kubernetes-e2e-gce-node-throughput
ci-kubernetes-e2e-gce-node-containerd-throughput
ci-kubernetes-e2e-windows-node-throughput
ci-kubernetes-e2e-windows-node-throughput-iis

in kubernetes/test-infra/config/jobs

Can you provide some hints or examples regarding how I should port them to Namespaces api?

**Comment by lyzs90** [comment]
@sgirem463 You can go ahead and assign yourself :)

**Comment by lyzs90** [comment]
These are the two configs where automanaged namespaces is still being used:
- https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/testing/node-throughput/config.yaml#L12
- https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/testing/windows-tests/config.yaml#L12

The jobs I mentioned above run off these configs. For example https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-scalability/sig-scalability-periodic-jobs.yaml#L47 references the node throughput config.

So the change you need to do is to switch over to use namespace instead i.e. https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/testing/load/config.yaml#L97. More details of the Namespace api can be found here: https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/api/types.go#L48

To verify your changes, we just need to make sure the jobs pass

**Comment by MadhavJivrajani** [comment]
> So the change you need to do is to switch over to use namespace instead i.e. https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/testing/load/config.yaml#L97

EDIT: the new location for reference is: https://github.com/kubernetes/perf-tests/blob/acaa23004ac96087cc7e12e2428a12b76be53e53/clusterloader2/testing/load/config.yaml#L80

**Comment by rahulii** [comment]
Hi @lyzs90 , so the `automanagedNamespaces` should be replaced with `namespace` in a similar manner to  https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/testing/load/config.yaml#L80 ?

**Comment by lyzs90** [comment]
@rahulii Yep that's right

**Comment by rahulii** [comment]
@lyzs90 , so after making changes how do I verify those changes ?

**Comment by JohnRusk** [comment]
As a new clusterLoader2 user, I'm suprised by the removal of automanagedNamespaces.  I thought it was a great feature.  Do understand correctly that it's being totally removed?  If so, why?

**Comment by JohnRusk** [comment]
Also, it this feature really is to be totally removed, then `docs/README.md` should be updated as part of this PR, since that document still quite clearly tells new users to rely on automanaged namespaces.
