### ISSUE TITLE
Is it possible to use self-deployed prometheus?

### ISSUE THREAD

**Issue by Jeffwan** [kubernetes/perf-tests#1713]
**What would you like to be added**:

Seems `prometheus` is a required dependency to run clusterloader2 tests. Otherwise, we will see lots of measurement were skipped. 

```
W0208 15:26:40.271637   74928 probes.go:106] InClusterNetworkLatency: Prometheus is disabled, skipping the measurement!
W0208 15:26:40.271665   74928 prometheus_measurement.go:59] APIResponsivenessPrometheusSimple: Prometheus is disabled, skipping the measurement!
W0208 15:26:40.271715   74928 prometheus_measurement.go:59] APIResponsivenessPrometheus: Prometheus is disabled, skipping the measurement!
W0208 15:26:40.271743   74928 probes.go:106] DnsLookupLatency: Prometheus is disabled, skipping the measurement!
```

Without specifying `--enable-prometheus-server`,  `prometheusFramework` never get value. However seems `SetUpPrometheusStack` and `prometheusFramework` initialization can be separate from the code logic here. 

https://github.com/kubernetes/perf-tests/blob/0d8e4738c869b8ee99bd8a31ee91d4a1f2b6f0ff/clusterloader2/cmd/clusterloader.go#L284-L294

Is it possible to create an prometheus controller without setup prometheus stack and use our own instead? I think in order to use custom prometheus, there're probably some conventions/changes to follow to make controller or measurement component work.

**Why is this needed**:

We need to make sure prometheus manifest is compatible with our cluster setting. Using existing prometheus is easier.

**Comment by mm4tt** [comment]
It's not currently supported, but I don't see any reason for not having such functionality. We'll happily accept contributions :) 

/good-first-issue
/help-wanted

**Comment by Jeffwan** [comment]
Got it. I will take this one. 

/assign

**Comment by wardenlym** [comment]
hi，i deploy kube-prometheus-stack with helm charts in my cluster,  

is there some workaround to let clusterloader detect which metrics stuff has been setup?

if there is something i can do for skipping the prometheus installing process,please let me know, many thanks.

**Comment by Jeffwan** [comment]
@wardenlym 

> is there any workaround to let clusterloader detect which metrics stuff has been set up?

detect which metrics? CL2 metrics gathers actually use standard control plane metrics exposed by apiserver and scheduler, etc. If your prometheus already collect these metrics. I think it should work out-of-box


> if there is something i can do for skipping the prometheus installing process,please let me know, many thanks.

Did you try to use  `--enable-prometheus-server` to skip prometheus setup?

**Comment by mm4tt** [comment]
@Jeffwan, are you actively working on this? Do you need any help?

**Comment by Jeffwan** [comment]
> @Jeffwan, are you actively working on this? Do you need any help?

I am not working on it recently and I remember I have piece of the work in the past. Let me revisit this one this week and report the status.
