### ISSUE TITLE
Storage class in Prometheus stack is binding to GCP

### ISSUE THREAD

**Issue by Jeffwan** [kubernetes/perf-tests#1723]
**What happened**:
Prometheus stack manifest doesn't use `default` storage class. Instead, it creates a separate storage class `ssd`. 
```
➜  ~ k get sc
NAME                      PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
....
ssd                       kubernetes.io/gce-pd    Delete          Immediate              false                  22s
```

The problem is storage provisioner is default to gcp's. It doesn't work in any platform.
https://github.com/kubernetes/perf-tests/blob/81f63e6a18b67e3469a854c678b532619c134078/clusterloader2/pkg/prometheus/manifests/0ssd-storage-class.yaml#L5-L7

Prometheus PVC results in pending and main process `Waiting for Prometheus stack to become healthy.` never move forward. 

```
Mounted By:    prometheus-k8s-0
Events:
  Type     Reason              Age   From                         Message
  ----     ------              ----  ----                         -------
  Warning  ProvisioningFailed  20s   persistentvolume-controller  Failed to provision volume with StorageClass "ssd": Failed to get GCE GCECloudProvider with error <nil>
➜  ~
```

**What you expected to happen**:
Either change to default storage class or add options to override gcp provisioner. 

**How to reproduce it (as minimally and precisely as possible)**:
Try to run CL2 with `--enable-prometheus-server`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by mm4tt** [comment]
Hey @Jeffwan, thank. you so much for opening this issues (and others). They are well documented and clearly explain a problem, it's great. 
Just a tiny ask, if you work on an issue (and I believe you do, given your PRs) could you assign it to you? :)

/assign @Jeffwan

**Comment by Jeffwan** [comment]
@mm4tt Ah, thanks for reminder. I will remember to assign issue to myself next time If I am working on it.
