### ISSUE TITLE
WaitForNodes does not consider nodes with taints

### ISSUE THREAD

**Issue by BigDarkClown** [kubernetes/perf-tests#1732]
**What happened**:

WaitForNodes only considers nodes without any NoSchedule/NoExecute taints. This makes nodes with taints from node-pools created by NAP not considered if they have any taint. In general, existence of such taints does not necessary mean that the node is "unschedulable".

**What you expected to happen**:

WaitForNodes would count nodes with NoSchedule/NoExecute taints.

**How to reproduce it (as minimally and precisely as possible)**:

* Create a node-pool with 0 nodes,  autoscaling and taint X=NoSchedule
* Create deployment with X=NoSchedule toleration
* Use WaitForNodes to count the nodes.

**Comment by lyzs90** [comment]
@wojtek-t Is there a reason why we [filter](https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/pkg/measurement/util/wait_for_nodes.go#L66) out tainted nodes? There was some history here https://github.com/kubernetes/perf-tests/pull/966/files#r362490911 about waiting for nodes to be ready - that can be satisfied by the [isNodeSchedulable](https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/pkg/util/cluster.go#L100) method alone?

**Comment by wojtek-t** [comment]
No - is NodeSchedulable isn't enough.

Many provider initially taint the node until some conditions are met (e.g. the node is correctly initialized, etc). You can't schedule anything on the tainted node anyway, and we're interested in nodes that are fully usable for us.

That said, this was addressed in: https://github.com/kubernetes/perf-tests/pull/1743

Closing.
