### ISSUE TITLE
Improve CL2 config validation

### ISSUE THREAD

**Issue by lyzs90** [kubernetes/perf-tests#1746]
Continuation of #1636. There's still a quite bit more we can validate, for instance:
- Ensure that steps are not empty
- Ensure that the tuning set referenced in a phase has been declared
- Implement verifyMeasuremen
  - APIAvailability, EtcdMetrics, Exec, MetricsForE2E, NodeLocalDNSLatencyPrometheus, etc... e
  - Each measurement may have custom parameters

You can link to this issue in your PR and comment here that you're working on certain packages to help avoid duplicated work.
Please do NOT put Fixes #... in your Pull Request. That will close this PR. Instead put Part of #1746.

**Comment by siddhartha97** [comment]
@lyzs90 newbie here, can I work on this? (:

**Comment by lyzs90** [comment]
@siddhartha97 Sure go ahead please :) Try to keep the PRs small. Eg  for verifyMeasurement, we can start off with one measurement first instead of tackling all at once.

**Comment by siddhartha97** [comment]
Will do! @lyzs90 Is there any specific directory i should be looking at in the repository to start off with _Implement verifyMeasurement_? 
/assign

**Comment by lyzs90** [comment]
Sorry it was renamed to validateMeasurement, you implement the function here: https://github.com/kubernetes/perf-tests/blob/b9e08a85e93daff53f1a68370cbbfa4de77dffe1/clusterloader2/api/validation.go#L180:27

Tests for validations are written here: https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/api/validation_test.go

The whole list of measurement can be found here: https://github.com/kubernetes/perf-tests/tree/b9e08a85e93daff53f1a68370cbbfa4de77dffe1/clusterloader2/pkg/measurement/common

An example of a test config is the [load test](https://github.com/kubernetes/perf-tests/blob/b9e08a85e93daff53f1a68370cbbfa4de77dffe1/clusterloader2/testing/load/config.yaml).

Off the top of my head, we can probably check that if a measurement is referenced in the [config](https://github.com/kubernetes/perf-tests/blob/b9e08a85e93daff53f1a68370cbbfa4de77dffe1/clusterloader2/testing/load/config.yaml#L134) then the corresponding measurement should have been [registered](https://github.com/kubernetes/perf-tests/blob/b9e08a85e93daff53f1a68370cbbfa4de77dffe1/clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go#L83). We could start with this general check before going into checking params for individual measurements.

Also, runtime checks like these could be moved to validation: https://github.com/kubernetes/perf-tests/blob/b9e08a85e93daff53f1a68370cbbfa4de77dffe1/clusterloader2/pkg/measurement/measurement_executor.go#L29

**Comment by mm4tt** [comment]
@siddhartha97, are you actively working on this? Do you need any help with reviews?

**Comment by rahulii** [comment]
@lyzs90 , I would like to work on this issue!

**Comment by lyzs90** [comment]
@rahulii go ahead please!

**Comment by rahulii** [comment]
> * Ensure that steps are not empty

Hi @lyzs90 , should i start with this and write a unit test for the same?

**Comment by rahulii** [comment]
> * Ensure that the tuning set referenced in a phase has been declared

I also wanted to get an understanding on this , does it mean that the tuning sets declared [here](https://github.com/kubernetes/perf-tests/blob/b9e08a85e93daff53f1a68370cbbfa4de77dffe1/clusterloader2/testing/load/config.yaml#L98) only those be refereneced in phase [here](https://github.com/kubernetes/perf-tests/blob/b9e08a85e93daff53f1a68370cbbfa4de77dffe1/clusterloader2/testing/load/config.yaml#L202)

**Comment by rahulii** [comment]
> > * Ensure that the tuning set referenced in a phase has been declared
> 
> I also wanted to get an understanding on this , does it mean that the tuning sets declared [here](https://github.com/kubernetes/perf-tests/blob/b9e08a85e93daff53f1a68370cbbfa4de77dffe1/clusterloader2/testing/load/config.yaml#L98) only those be refereneced in phase [here](https://github.com/kubernetes/perf-tests/blob/b9e08a85e93daff53f1a68370cbbfa4de77dffe1/clusterloader2/testing/load/config.yaml#L202)

/cc @marseel

**Comment by lyzs90** [comment]
> I also wanted to get an understanding on this , does it mean that the tuning sets declared here only those be refereneced in phase here

@rahulii Your understanding here is correct. The test would [fail](https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/pkg/test/simple_test_executor.go#L188) mid execution when it tries to create a tuning set which can't be found.

**Comment by rahulii** [comment]
> > I also wanted to get an understanding on this , does it mean that the tuning sets declared here only those be refereneced in phase here
> 
> @rahulii Your understanding here is correct. The test would [fail](https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/pkg/test/simple_test_executor.go#L188) mid execution when it tries to create a tuning set which can't be found.

So the general idea would be to check :
```
loop through Steps.Phases.tuningSet 
    loop through tuningSets
        check if Steps.Phases.tuningSet is present
```
What do you think @lyzs90 ?

**Comment by marseel** [comment]
@rahulii Looks good to me.

**Comment by rahulii** [comment]
> Off the top of my head, we can probably check that if a measurement is referenced in the [config](https://github.com/kubernetes/perf-tests/blob/b9e08a85e93daff53f1a68370cbbfa4de77dffe1/clusterloader2/testing/load/config.yaml#L134) then the corresponding measurement should have been [registered](https://github.com/kubernetes/perf-tests/blob/b9e08a85e93daff53f1a68370cbbfa4de77dffe1/clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go#L83). We could start with this general check before going into checking params for individual measurements.
> 
@marseel  @lyzs90 , how do i check if the measurement has been registered or not?

**Comment by marseel** [comment]
@rahulii 
Here you can find factory in which all measurements are registered: https://github.com/kubernetes/perf-tests/blob/b9e08a85e93daff53f1a68370cbbfa4de77dffe1/clusterloader2/pkg/measurement/factory.go
What I propose is:
- Adding new method to measurementFactory that checks if measurement with specific name is registered. 
- Adding new function "IsRegistered(methodName string)" that returns true/false. This method should use method implemented above. 
- Using this new function in validation.

**Comment by rahulii** [comment]
> @rahulii
> Here you can find factory in which all measurements are registered: https://github.com/kubernetes/perf-tests/blob/b9e08a85e93daff53f1a68370cbbfa4de77dffe1/clusterloader2/pkg/measurement/factory.go
> What I propose is:
> 
> * Adding new method to measurementFactory that checks if measurement with specific name is registered.
> * Adding new function "IsRegistered(methodName string)" that returns true/false. This method should use method implemented above.
> * Using this new function in validation.

@marseel ,  so i tried implementing this approach , and I'm facing one issue `import cycle not allowed`
So . the measurement package uses `api` package somewhere (validation.go is in api package) and when I import the measurement package , it gives the above error!

**Comment by marseel** [comment]
@rahulii Could you create draft PR so I can take a look?
