### ISSUE TITLE
Cannot run load test at scale smaller than 100 nodes

### ISSUE THREAD

**Issue by tosi3k** [kubernetes/perf-tests#1752]
https://github.com/kubernetes/perf-tests/pull/1667 has made it possible to run the load test in clusters with less than 100 worked nodes (meaning having the `--nodes` CL2 flag set to a value lower than 100).

After the introduction of https://github.com/kubernetes/perf-tests/pull/1694, running the load test from the current master branch results in the following error, though:
```
Test compliation failed: [tuningSets[1].parallelismLimitedLoad.parallelismLimit: Invalid value: 0: must have positive value]
```

This fail is understandable - we cannot validate the `SchedulerThroughputParallel` tuning set as we have `parallelismLimit` being set to 0:
```
{{$IS_SMALL_CLUSTER := lt .Nodes 100}}
(...)
{{$schedulerThroughputNamespaces := IfThenElse $IS_SMALL_CLUSTER 0 $schedulerThroughputNamespaces}}
(...)
tuningSets:
(...)
- name: SchedulerThroughputParallel
  parallelismLimitedLoad:
    parallelismLimit: {{$schedulerThroughputNamespaces}}
```

/cc @lyzs90

**Comment by lyzs90** [comment]
Ah my bad. In this case, it should be okay to add the not small cluster condition over the offending tuning set, since it's only being used within the scheduler throughput steps.
