### ISSUE TITLE
Why not to use Prometheus measurement for all metrics

### ISSUE THREAD

**Issue by Jeffwan** [kubernetes/perf-tests#1778]
**What would you like to be added**:

I feel like there're multiple ways to fetch metrics. using scheduler metrics as an example

https://github.com/kubernetes/perf-tests/blob/54890c1864c6e6c68295a520270f10ac1bcb907e/clusterloader2/pkg/measurement/common/scheduler_latency.go#L297-L321

https://github.com/kubernetes/perf-tests/blob/54890c1864c6e6c68295a520270f10ac1bcb907e/clusterloader2/pkg/measurement/common/scheduling_throughput_prometheus.go#L76

Based on different options, it may 
1. use rest client to fetch metrics
2. SSH into master and curl https port. 
3. In the past, if insecure port is still open, it can send a curl request against master directly 
4. PromQuery against pre-installed Prometheus server. 

**Why is this needed**:

To create a test bundle, we have to check each metrics clearly to see if it's supported in user's environment. 
Can you unified a way like all metrics should be scratched from prometheus instead?

**Comment by wojtek-t** [comment]
For scheduler - we indeed would like ot migrate to prometheus:
https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/pkg/measurement/common/scheduling_throughput_prometheus.go

It just requires figuring out a couple things to launch it.
