### ISSUE TITLE
Support more kube-apiserver metrics 

### ISSUE THREAD

**Issue by Jeffwan** [kubernetes/perf-tests#1779]
**What would you like to be added**:
We have a few API server related metrics

- api_availability_metrics.go
- api_availability_measurement.go
- api_responsiveness_prometheus.go

Seems `apiserver_request_count` and `apiserver_request_latencies_bucket` are not supported in any measurement yet.

Am I missing something? If we this part is helpful, I can help on this issue. 

**Why is this needed**:

**Comment by Jeffwan** [comment]
seems `kube-controller-manager` related metrics are not there as well.

**Comment by wojtek-t** [comment]
> Seems apiserver_request_count and apiserver_request_latencies_bucket are not supported in any measurement yet.

The latter is part of api_responsiveness.
The former - how you would like to use it? What exactly you would like to check?

If you just want visibility to metrics, those are gathered from metrics e2e:
https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/pkg/measurement/common/metrics_for_e2e.go
