### ISSUE TITLE
Network Performance tests: negative UDP latency values for some test runs.

### ISSUE THREAD

**Issue by VivekThrivikraman-est** [kubernetes/perf-tests#1818]
**What happened**:
UDP latency metrics collected while running network performance test cases (clusterloader2/testing/network) intermittently contains negative values.

**What you expected to happen**:
UDP latency should be always positive.

**How to reproduce it (as minimally and precisely as possible)**:
Issue is not seen when running locally in Kind or local vm cluster. Negative values are seen when the testcases are run in k8s CI/CD(GCE).

**Anything else we need to know?**:
It is  confirmed from the logs that Iperf2 tool which is used for collecting the metrics return these -ve values. Raised this in iperf2 forum :
https://sourceforge.net/p/iperf2/discussion/general/thread/a1bcdb67d8/

They suspect this to be clock synchronization issue(they mentioned NTP synchronized nodes also can have latency).

Aggregated metrics output for UDP attached:
[NetworkPerformanceMetrics_N_M_UDP_P2P_network_performance_udp-50_50_2021-05-21T08_39_04Z.json.txt](https://github.com/kubernetes/perf-tests/files/6568363/NetworkPerformanceMetrics_N_M_UDP_P2P_network_performance_udp-50_50_2021-05-21T08_39_04Z.json.txt)

**Environment**:
Testcases are run as part of prow job in k8s CI/CD, in GCE.

**Comment by aojea** [comment]
We've been talking about this in slack, and since the VM synchronisation seems complex problem to fix , we though that the best solution moving forward will be to gather more data to get better insights, maybe we only need the trend and not the absolute values.

The doubt that we have is if it would be good to operate only with positive numbers, i.e. truncate negative values to 0

@wojtek-t what do you think?

**Comment by wojtek-t** [comment]
We do clock-synchronization in GCE - I personally doubt it's clock difference. I bet it's a real bug...

**Comment by VivekThrivikraman-est** [comment]
@wojtek-t is it NTP ?

**Comment by hanamantagoudvk** [comment]
@wojtek-t @aojea : What do you think of considering negative values as zero. ? Shall we proceed with that idea ?

**Comment by mm4tt** [comment]
It's NTP - https://cloud.google.com/compute/docs/instances/managing-instances#configure-ntp

**Comment by VivekThrivikraman-est** [comment]
Thanks @mm4tt , as you mentioned we will first fix perfdash and monitor to make sure latency is always in microseconds and then make a decision.

**Comment by aojea** [comment]
> Thanks @mm4tt , as you mentioned we will first fix perfdash and monitor to make sure latency is always in microseconds and then make a decision.

http://perf-dash.k8s.io/#/?jobname=network-performance&metriccategoryname=Network_Baseline&metricname=UDP_P2P&Metric=Latency
