### ISSUE TITLE
Use single node test with config file `./testing/load/config.yaml` report an error When testing clusterloader2 locally

### ISSUE THREAD

**Issue by yangjunmyfm192085** [kubernetes/perf-tests#1832]
**What happened**:
Use single node test with config file `./testing/load/config.yaml` report an error When testing clusterloader2 locally, I got the error message:
F0613 23:24:54.654528  225726 clusterloader.go:337] Test compliation failed: [tuningSets[5].randomizedTimeLimitedLoad.timeLimit: Invalid value: 0: must have positive value]

**What you expected to happen**:
No errors.

**How to reproduce it (as minimally and precisely as possible)**:
run clusterloader2 test use the command
 ./run-e2e.sh --testconfig=./testing/load/config.yaml --provider=gce --enable-prometheus-server=true --masterip=127.0.0.1 
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by wojtek-t** [comment]
@marseel - can you please take a look - it is kind-of related to the starting guide you're creating

/assign @marseel 

@mm4tt - FYI

**Comment by marseel** [comment]
I am aware of this issue, it's related to this issue: #1759
To sum up:
- Running load test with < 100 nodes worked before
- We don't have any CI/presubmit that checks it
- After some time it stopped working

So I would propose:
- Fixing load test for < 100 nodes scale
- Adding presubmit for 1 node.

**Comment by eddycharly** [comment]
I'm hitting the same issue, any workaround ?
