### ISSUE TITLE
Fail to build k8s.io/perf-tests/golang and push to k8s-infra-scale-golang-builds

### ISSUE THREAD

**Issue by ameukam** [kubernetes/perf-tests#1861]
**Which jobs are failing**:
ci-build-and-push-k8s-at-golang-tip-canary

**Which test(s) are failing**:

**Since when has it been failing**:

**Testgrid link**:
https://testgrid.k8s.io/wg-k8s-infra-canaries#build-and-push-k8s-at-golang-tip-canary

**Reason for failure**:
I wasn't unable to identify the reason of the failure.

**Anything else we need to know**:
Part of https://github.com/kubernetes/k8s.io/issues/2241
Canary job of `ci-build-and-push-k8s-at-golang-tip` to ensure we can migrate it to the community-owned k8s infrastructure.

/assign @tosi3k @marseel

**Comment by ameukam** [comment]
Ref: https://github.com/kubernetes/k8s.io/issues/2268

**Comment by marseel** [comment]
@tosi3k Could you take a look at it please, as you are our golang test expert ;) ?

**Comment by tosi3k** [comment]
Hey, sorry for the lack of response, I was CCed here when I was on a longer leave and then the issue got lost in my mailbox :/.

I promise to take a deeper look at this later this week.

**Comment by ameukam** [comment]
First successful build : https://storage.googleapis.com/kubernetes-jenkins/logs/ci-build-and-push-k8s-at-golang-tip-canary/1429096348275183616/build-log.txt

```shell
 gsutil cat gs://k8s-infra-scale-golang-builds/ci/latest-1.18.txt
v1.18.3-beta.0.8+13a714624f9946
```
