### ISSUE TITLE
Add scalability metrics for output Prometheus metrics to detect cardinality regressions

### ISSUE THREAD

**Issue by ehashman** [kubernetes/perf-tests#1870]
**What would you like to be added**:

We recently detected and reverted a cardinality explosion in 1.22 that caused a significant memory regression in a cluster-scraping Prometheus:

- [SIG Instrumentation Meeting Minutes](https://docs.google.com/document/d/1FE4AQ8B49fYbKhfg4Tx0cui1V0eI4o3PxoqQPUwNEiU/edit#bookmark=id.gbt7ediwramw)
- https://github.com/kubernetes/kubernetes/issues/104008

The issue was only detected in a downstream distribution (OpenShift) during upgrade testing for 1.22. Despite being merged in April, it was not caught in upstream Kubernetes tests until a week before release.

**Why is this needed**:

We need a way to detect metric cardinality regressions in a Kubernetes cluster before release.

Scalability tests already run a Prometheus instance. We'd like to suggest collecting a metric on the cardinality (e.g. number of timeseries) of metrics available in a cluster as part of the perf-tests, so we can easily catch regressions that add too many timeseries due to e.g. label cardinality issues.

**Comment by marseel** [comment]
I see that the problem with this metric was due to namespaces. Currently, our scalability test creates O(50) namespaces. Also, I've checked that in our load tests this metric is only generated for 1 namespace "monitoring" so unfortunately this regression would not be detected.  Generally I am supportive for checking cardinality in load test.

**Comment by aojea** [comment]
I think that at this point is a problem of just having a mechanism to detect this cardinality problem, we can iterate later on the scenarios, you have a nice and flexible API with ClusterLoader2.

What will be the best way to implement this "cardinality explosion detection" feature in perf-tests? 
I'm out of my expertise area here
