### ISSUE TITLE
Delete namespaces more rapidly when they contain lots of events

### ISSUE THREAD

**Issue by JohnRusk** [kubernetes/perf-tests#1872]
**Suggested addition**

When deleting namespaces at the end of the test, ClusterLoader2 should first delete all the events in the namespace.  If the code deletes many events in parallel, it will make cleanup much quicker.    I'm happy to create a PR, but have some questions first (below).

**Why**

I've noticed that clusterLoader2 is taking many minutes to clean up at the end of my tests.  E.g. at least 5 to 10 minutes to delete the namespace that was used in the test.  This is because my test generates lots of events.  It appears that a simple call to Kubernetes to delete a namespace is not very quick when the namespace contains lots of events.  However, I tested code which explicitly deletes the events first (processing a few hundred events in parallel).  This runs an order of magnitude more quickly.

**Questions**

I'm happy to submit a PR, but I have a design question first: how should the degree of parallelism be controlled?  Options that come to mind include

1. Just hard code something.  E.g. 100 concurrent deletion operations. (I.e. 100 goroutines, each deleting one event at a time).
2. Use a `tuningSet`.  This seems like the most idomatic clusterLoader2 approach... but... I can't think of a nice way to link a tuningSet to the automatic deletion of namespaces.
3. Use some other parameter, e.g. `eventCleanupRate` in the CL2 `namespaces` object.  That's simpler, but seems awfully specific to the details of this particular problem.
4. Use a command line parameter, with a default value.  This may in fact be the simplest option.  It won't clutter the CL2 test definition API, and a sensible default can be provided.

Does anyone have any thoughts on which might be the best way?  If we can settle on an approach, I'll submit a PR.

**Comment by marseel** [comment]
Thanks cool idea, I like it. 

Out of these 4 options I like 4th most. Let's make it in a way that if someone does not specify it we won't explicitly delete events. 
So I would have default 0, which would mean that this feature is turned off and if someone wants to enable it they can. 
This will also allow us to safely deploy it (as we have multiple tests with different sizes of masters, so the same rate won't be good for all tests).
I've also checked that deleting namespaces takes around ~50s in our scalability tests for 5k nodes so in our case it might not be worth changing it as tests take around 5h to complete. 

Also, I am happy to review your changes.

**Comment by JohnRusk** [comment]
@marseel  That's a great idea about making the default be zero.

I have created the PR.  Looks like I don't have rights to assign you as a reviewer. Can you assign yourself? Or just go ahead and review it?

**Comment by marseel** [comment]
I've assigned myself on PR, I will review it on Monday. Also, I've noticed that you need to sign CLA.

**Comment by wojtek-t** [comment]
I'm against this change - it's already possible at the cluster level:

https://github.com/kubernetes/perf-tests/pull/1874#discussion_r693931883
