### ISSUE TITLE
Migrate sig-scalability jobs to k8s-infra

### ISSUE THREAD

**Issue by ameukam** [kubernetes/perf-tests#1898]
Part of umbrella issue to migrate away from google.com gcp projects: https://github.com/kubernetes/k8s.io/issues/1469

We should migrate away from Google scalability projects and use community-owned GCP projects. 

We start first with the periodics. 

Jobs to be migrated:

Merge-blocking:
- [x] ci-kubernetes-e2e-gce-scale-correctness : https://github.com/kubernetes/test-infra/pull/24080
- [x] ci-kubernetes-e2e-gce-scale-performance : https://github.com/kubernetes/test-infra/pull/23807

Non merge-blocking
- [X] ci-kubernetes-e2e-gce-node-throughput : https://github.com/kubernetes/test-infra/pull/23759 (@ameukam) 
- [X] ci-kubernetes-e2e-gce-node-containerd-throughput : https://github.com/kubernetes/test-infra/pull/23759 (@ameukam)
- [X] ci-kubernetes-kubemark-100-gce : https://github.com/kubernetes/test-infra/pull/23716 (@ameukam)
- [X] ci-kubernetes-kubemark-100-gce-scheduler : https://github.com/kubernetes/test-infra/pull/23805
- [ ] ci-kubernetes-kubemark-100-gce-scheduler-highqps : perma-failing ?
- [X] ci-kubernetes-kubemark-500-gce: https://github.com/kubernetes/test-infra/pull/23806
- [X] ci-kubernetes-kubemark-gce-scale : https://github.com/kubernetes/test-infra/pull/23844
- [X] ci-kubernetes-kubemark-gce-scale-scheduler : https://github.com/kubernetes/test-infra/pull/23844
- [X] ci-kubernetes-kubemark-high-density-100-gce : https://github.com/kubernetes/test-infra/pull/23844
- [X] ci-perf-tests-kubemark-100-benchmark: https://github.com/kubernetes/test-infra/pull/23762 (@ameukam)
- [X] ci-benchmark-scheduler-master : https://github.com/kubernetes/test-infra/pull/23763
- [X] ci-benchmark-scheduler-perf-master : https://github.com/kubernetes/test-infra/pull/23763
- [X] ci-benchmark-kube-dns-master : https://github.com/kubernetes/test-infra/pull/23782 
- [X] ci-benchmark-nodelocal-dns-master : https://github.com/kubernetes/test-infra/pull/23782
- [ ] ~ci-benchmark-microbenchmarks~: https://github.com/kubernetes/test-infra/pull/25999
- [x] ci-kubernetes-e2e-gce-network-metric-measurement : https://github.com/kubernetes/test-infra/pull/24079
- [ ] ci-kubernetes-e2e-scalability-cleanup
- [ ] ci-kubernetes-storage-scalability: perma-failing ? 
- [x] ci-kubernetes-e2e-gci-gce-scalability-networkpolicies : https://github.com/kubernetes/test-infra/pull/24079
- [ ] ci-kubernetes-e2e-gci-gce-scalability-node-killer : 
- [X] ci-build-and-push-k8s-at-golang-tip : https://github.com/kubernetes/test-infra/pull/25293
- ~[ ] ci-golang-tip-k8s-1-18~: https://github.com/kubernetes/test-infra/pull/24035
- [X] ci-golang-tip-k8s-1-23: https://github.com/kubernetes/test-infra/pull/25296

/sig k8s-infra
/sig scalability
/sig testing

**Comment by mborsz** [comment]
@ameukam 

ci-kubernetes-kubemark-500-gce failed with the same error today:
```
 - Quota 'CPUS' exceeded.  Limit: 72.0 in region us-central1.

```
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/1446454273704464384

That run used project: k8s-infra-e2e-boskos-scale-02

Can we increase quota there as well?

**Comment by mborsz** [comment]
Tests are still flaking: Example today: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/1447784989184757760


It used k8s-infra-e2e-boskos-scale-02 again.

@ameukam, can we increase quota in all projects used in kubemark-500 tests?
