### ISSUE TITLE
404, network/benchmarks/netperf/images/BenchmarkingKubernetesNetworkingPerformance.svg

### ISSUE THREAD

**Issue by CodeJuan** [kubernetes/perf-tests#19]
In [network/benchmarks/netperf/README.md](https://github.com/kubernetes/perf-tests/blob/master/network/benchmarks/netperf/README.md), the urls of 
[svg, e.g. netperf.svg & BenchmarkingKubernetesNetworkingPerformance.svg](https://github.com/kubernetes/perf-tests/raw/master/network/benchmarks/netperf/images/netperf.svg) are 404

Thanks :smile:

**Comment by gmarek** [comment]
Yeah... they're not there, probably because of .gitignore rules. As we lost an owner @girishkalele and I don't think I have any idea how to recover those diagrams. Sorry :(

@thockin @matchstick - do you have those diagrams anywhere by any chance?
