### ISSUE TITLE
kubemark-500 test should not use exempt priority level

### ISSUE THREAD

**Issue by tkashem** [kubernetes/perf-tests#1920]
**What happened**:

after analyzing the `httplog` entries from a kubemark-500 test job, we see a lot of requests using the `exempt` priority level.  Using a limited priority level with a concurrency limit (`workload-low` priority level for example) will put apf to the test.  

If my calculation is correct, roughly 25% of the requests use the exempt priority level.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by wojtek-t** [comment]
I'm closing in favor of https://github.com/kubernetes/kubernetes/issues/104809
