### ISSUE TITLE
Dnsperfgo image should be build in isolated environment

### ISSUE THREAD

**Issue by marseel** [kubernetes/perf-tests#2001]
Dnsperfgo is currently build on host machine and not in isolated environment: https://github.com/kubernetes/perf-tests/blob/edbd49ced99afdc71555a3d028cfbb8f46490f43/dns/dnsperfgo/Makefile#L13
then it's copied to image: https://github.com/kubernetes/perf-tests/blob/edbd49ced99afdc71555a3d028cfbb8f46490f43/dns/dnsperfgo/Dockerfile#L7

We should build binary in isolated env, just like we do for sleep image: https://github.com/kubernetes/perf-tests/blob/edbd49ced99afdc71555a3d028cfbb8f46490f43/util-images/sleep/Dockerfile#L1

/good-first-issue

**Comment by uroy-personal** [comment]
Hi @marseel ,
I am interested to work on this. If it is not being worked upon at the moment, please let me know.

**Comment by marseel** [comment]
Sounds good.
/assign @uroy-personal 

Let me know if you need any help. Easiest way to contact me is on Slack.

**Comment by uroy-personal** [comment]
> Sounds good. /assign @uroy-personal
> 
> Let me know if you need any help. Easiest way to contact me is on Slack.

Thanks @marseel , I will reach out to you on Slack.

**Comment by uroy-personal** [comment]
Thanks @marseel  for providing me the opportunity to work on the issue. I learned a lot in this project. I have raised a pull request (https://github.com/kubernetes/perf-tests/pull/2011) for the fix. Please have a look to the changes and suggest potential modifications needed. 

Thanks again.
