### ISSUE TITLE
Delete Namespace sometimes failed

### ISSUE THREAD

**Issue by FANHIDE** [kubernetes/perf-tests#2081]
**What happened**:
Failed to delete the namespace generated according to the prefix

**What you expected to happen**:
Always can delete namespace 

**How to reproduce it (as minimally and precisely as possible)**:
`namespace:
  number: {{$namespacesNumber}}
  prefix: test
  deleteAutomanagedNamespaces: true
  enableExistingNamespaces: true`

**Anything else we need to know?**:

**Environment**: test
- Kubernetes version (use `kubectl version`): 1.20.15
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by JohnRusk** [comment]
This may be relevant. https://github.com/kubernetes/perf-tests/pull/1874

(try listing all the events in one of the failed namespaces, to see if there is lots of them)

**Comment by FANHIDE** [comment]
> This may be relevant. #1874
> 
> (try listing all the events in one of the failed namespaces, to see if there is lots of them)
Thx , It is not relevant.
I debugged, I found that sometimes delete the same namespace
