### ISSUE TITLE
apiAvailabilityMetrics.update need reset consecutiveFailedProbes when availability is true

### ISSUE THREAD

**Issue by neiba** [kubernetes/perf-tests#2092]
**What happened**:
https://github.com/kubernetes/perf-tests/blob/277b8658acc36883fd1efe5e68b3d7a9f252bcc9/clusterloader2/pkg/measurement/common/api_availability_metrics.go#L41-L51

should we set a.consecutiveFailedProbes = 0 when availability is true ?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by marseel** [comment]
yup, seems like it's a bug
/assign @tosi3k 
/remove-lifecycle rotten
