### ISSUE TITLE
NetworkProgrammingLatency - NetworkProgrammingLatency error: got unexpected number of samples: 0

### ISSUE THREAD

**Issue by leroylim20** [kubernetes/perf-tests#2170]
**What happened**:
Getting consistent failed test 

`NetworkProgrammingLatency - NetworkProgrammingLatency error: got unexpected number of samples: 0`

**What you expected to happen**:
Samples to be received for NetworkProgrammingLatency

**How to reproduce it (as minimally and precisely as possible)**:
Running Clusterloader2 on EKS > 1.20 with the following command 

`./run-e2e-with-prometheus-fw-rule.sh cluster-loader2 --testconfig=./testing/load/config.yaml --nodes=20 --provider=eks --enable-prometheus-server=true --kubeconfig=${HOME}/.kube/config --v=2 --report-dir=reports/`

**Anything else we need to know?**:
Running with parameters
```
"PROMETHEUS_STORAGE_CLASS_PROVISIONER", "kubernetes.io/aws-ebs"
"PROMETHEUS_STORAGE_CLASS_VOLUME_TYPE", "gp2"
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.23
- Cloud provider or hardware configuration: EKS
- OS (e.g: `cat /etc/os-release`): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by marseel** [comment]
I am unfortunately unable to test it on EKS, but hopefully @shyamjvs can help

/assign @shyamjvs

**Comment by marseel** [comment]
As temporary workaround you can set `export PROMETHEUS_SCRAPE_KUBE_PROXY=false` before running CL2
