### ISSUE TITLE
net.LookupHost making additional AAAA query

### ISSUE THREAD

**Issue by jlunaq** [kubernetes/perf-tests#2197]
Hello,
I'm using the dnsperfgo tool, and when I run it from the Docker container with bind-utils installed, I see that is making some additional AAAA queries for each record. Is there a way to workaround this?

**Comment by marseel** [comment]
Dorde, could you take a look at it as you are most familiar with dnsperfgo ?
/assign @dlapcevic

**Comment by dlapcevic** [comment]
Hi. The short answer is there is currently no configuration for it in dnsperfgo.

dnsperfgo uses the DNS resolver client which is configured to send both A and AAAA queries in parallel.
We would have to replace net.LookupHost, and use another library to avoid this.

In K8s, it is possible to configure `ndots` field of pods to reduce the scope of searchpath expansion, and also reduce the number of parallel queries. https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config
