### ISSUE TITLE
Default image on netperf is not working correctly

### ISSUE THREAD

**Issue by cristure** [kubernetes/perf-tests#2257]
**What would you like to be added**:

If you launch the tests with the default image, the pods will be in an error state because the default image does not have the testFrom flag defined. Also in the README there is another image (presumably older default image) claiming to be the default one. However both of these have the same issue.

**Why is this needed**:

Launching the tests should be a straightforward experience and only if the user wishes to modify the current behaviour should use a different image. At this state there is no working example, therefore obliging the end-user to build its own image from the start.

**Comment by cloudziu** [comment]
Any progress on this?
