### ISSUE TITLE
Add module to exercise list calls in CL2

### ISSUE THREAD

**Issue by mengqiy** [kubernetes/perf-tests#2275]
**What would you like to be added**:

Clusterloader2 seems to lack tests to exercise list calls.

**Why is this needed**:

We have an SLO for list calls in https://github.com/kubernetes/community/blob/master/sig-scalability/slos/api_call_latency.md. But CL2 doesn't explicitly exercise it.

**Comment by anson627** [comment]
> **What would you like to be added**:
> 
> Clusterloader2 seems to lack tests to exercise list calls.
> 
> **Why is this needed**:
> 
> We have an SLO for list calls in https://github.com/kubernetes/community/blob/master/sig-scalability/slos/api_call_latency.md. But CL2 doesn't explicitly exercise it.

agree, list calls are the most expensive, and  most likely to overload API server

**Comment by mengqiy** [comment]
[watch-list](https://github.com/kubernetes/perf-tests/tree/master/clusterloader2/testing/watch-list) sololy exercises the list calls. We can leverage it be embed it in the load test to create a mixture of all workload types.
