### ISSUE TITLE
clusterload - the server is currently unable to handle the request

### ISSUE THREAD

**Issue by douxiaoniu77** [kubernetes/perf-tests#2294]
Run following commands for clusterload test:
clusterloader --testconfig=/home/xueniu/perf-tests/clusterloader2/testing/density/config.yaml --masterip=###    --master-internal-ip=###   --mastername=dxhmas1 --provider=kubemark --kubeconfig=/root/.kube/config --report-dir=./reports --alsologtostderr

**What happened**:

It ran into following error 
I0627 11:21:40.256562     985 clusterloader.go:239] Running /home/xueniu/perf-tests/clusterloader2/testing/density/config.yaml
I0627 11:21:40.256566     985 clusterloader.go:240] --------------------------------------------------------------------------------
W0627 11:21:40.269407   985 prometheus_measurement.go:68] APIResponsivenessPrometheusSimple: Prometheus is disabled, skipping the measurement!
W0627 11:21:40.269443     985 prometheus_measurement.go:68] APIResponsivenessPrometheus: Prometheus is disabled, skipping the measurement!
E0627 11:21:40.298126     985 scheduler_latency.go:314] Send request to scheduler failed with err: the server is currently unable to handle the request (get pods https:kube-scheduler-dxhmas1:10251)
E0627 11:21:40.466383     985 test_metrics.go:250] TestMetrics: [action start failed for SchedulingMetrics measurement: the server is currently unable to handle the request (get pods https:kube-scheduler-dxhmas1:10251)]
W0627 11:21:40.466558     985 simple_test_executor.go:174] Got errors during step execution: [measurement call TestMetrics - TestMetrics error: [action start failed for SchedulingMetrics measurement: the server is currently unable to handle the request (get pods https:kube-scheduler-dxhmas1:10251)]]

**What you expected to happen**:
Get the scheduler metrics successfully 

**How to reproduce it (as minimally and precisely as possible)**:
Always

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):  1.18.4
- Cloud provider or hardware configuration:  kubemark 
- OS (e.g: `cat /etc/os-release`):  centos 
- Kernel (e.g. `uname -a`):   4.19
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by douxiaoniu77** [comment]
Similar issue with https://github.com/kubernetes/perf-tests/issues/1885

**Comment by douxiaoniu77** [comment]
Could anyone please help on the issue and finger out the solution? Thanks in advance ~

**Comment by Jont828** [comment]
@douxiaoniu77 @logabot Did you end up finding a way for this to work out of the box?

**Comment by Jont828** [comment]
I'm using kubeadm for the control plane and had the same issue. I found this [issue](https://github.com/kubernetes/kubernetes/issues/114543) where they explained you need to change the kube scheduler bind address from 127.0.0.1 by default to 0.0.0.0. I'm guessing it was always 0.0.0.0 for users who didn't have this error.
