### ISSUE TITLE
netperf documentation

### ISSUE THREAD

**Issue by extravio** [kubernetes/perf-tests#2452]
**What would you like to be added**:
Can we add a "Get started" section to the README on the netperf tool to describe how to set up the components?

**Why is this needed**:
I get the following error in the orchestrator's logs:

> flag provided but not defined: -testFrom

and the pod doesn't start

**Comment by Avnshrai** [comment]
`flag provided but not defined: -testFrom`
how to fix this issue? I am also facing same issue

**Comment by bernardgut** [comment]
@extravio @Avnshrai  did any of you ever figure this out ?

**Comment by justin0u0** [comment]
The [default image](https://github.com/kubernetes/perf-tests/blob/ed23e6281e12905924fe3aff2a52a8b3a1c7eef6/network/benchmarks/netperf/launch.go#L77) hasn't been updated for a while. You can build the image manually and set the image tag on launch with the following steps:

```bash
docker build . -t netperf:latest --build-arg GOLANG_VERSION=1.22-bullseye
go run launch.go -image netperf:latest
```

**Comment by AlexanderDotH** [comment]
Thanks for posting a resolution. I just built the image and ran the launch command. Somehow my pods are Pending but nothing happens. 
![image](https://github.com/user-attachments/assets/aff6830f-4205-470b-8ddd-1a204181a148)

**Comment by justin0u0** [comment]
> Thanks for posting a resolution. I just built the image and ran the launch command. Somehow my pods are Pending but nothing happens.

Hi @AlexanderDotH,

A "Pending" status generally indicates that the pod is unable to be scheduled onto a node. You can describe the pod to get more information. Typically this is not related to the application itself.

For more details, you can refer to https://kubernetes.io/docs/tasks/debug/debug-application/debug-pods/#my-pod-stays-pending.

Hope this helps!

**Comment by extravio** [comment]
@bernardgut @Avnshrai 
I managed to make it work thanks to this:
https://www.linkedin.com/pulse/testing-network-performance-iperf3-kubernetes-ghassan-malke-/
