### ISSUE TITLE
Move to distroless images instead of alpine

### ISSUE THREAD

**Issue by aojea** [kubernetes/perf-tests#2491]
Specially for DNS since it uses muslc that diverges from libc and has different behavior on the resolver implementation

https://github.com/GoogleContainerTools/distroless

https://github.com/kubernetes/perf-tests/blob/82036a7e9bdb803b5b133c2d83cfec710819f9ab/dns/dnsperfgo/Dockerfile#L11

**Comment by ameukam** [comment]
Distroless don't allow us to easily install tcpdump and dns-tools ?

**Comment by aojea** [comment]
> Distroless don't allow us to easily install tcpdump and dns-tools ?

this is mainly for the ones that are created for a golang binary only
