### ISSUE TITLE
Clusterloader2 is not compatible with go v1.11

### ISSUE THREAD

**Issue by orsoly** [kubernetes/perf-tests#254]
I'm trying to upgrade go version to 1.11, but the Travis CI fails. The merge of pull request #229 created this problem.

The error output of ./verify/verify-gofmt.sh
```
!!! 'gofmt -s' needs to be run on the following files: 
./clusterloader2/pkg/measurement/common/resource_usage.go
./clusterloader2/pkg/measurement/util/gatherers/resource_gather_worker.go
The command "./verify/verify-gofmt.sh" exited with 1
```
These two files have problem with indentation.

- resource_usage.go in line 83 and 84
- resource_gather_worker.go in line 56

**Comment by krzysied** [comment]
@orsoly I cant't fix clusterloader2 files cause there are correctly formatted (according to the current go version). Could you run `gofmt -w` on  `./clusterloader2/pkg/measurement/common/resource_usage.go` and `./clusterloader2/pkg/measurement/util/gatherers/resource_gather_worker.go` and commit those changes as a part of your RP, please?

**Comment by orsoly** [comment]
@krzysied, thanks for your answer. I created a commit in my PR that fixes these errors.
