### ISSUE TITLE
Travis is unhappy

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/perf-tests#26]
Seems like Travis is failing always due to `go get ./...` and `go test ./..` commands run against the repo.
This is because we use glide as our dep manager instead of godep in `clusterloader` which works differently.
We need to fix this by doing one of the following:
- Use glide's get and test equivalents for clusterloader and go for all the other directories
- Move clusterloader to godep, so we have uniformity across the whole repo

cc @kubernetes/sig-scalability-misc @gmarek @spxtr

**Comment by gmarek** [comment]
@sjug - it's failing on Godeps for cluster loader. Can you fix that?

**Comment by sjug** [comment]
@gmarek `clusterloader` has it's own vendor directory in `./clusterloader` that seems to be the issue.

I'm not sure why the package has issues I'm taking a look into it now, but in the meantime maybe: https://github.com/golang/go/issues/11659#issuecomment-171678025
```
go get $(go list ./... | grep -v /vendor/)
go test $(go list ./... | grep -v /vendor/)
```

**Comment by timothysc** [comment]
godep smashing e2e staging dep-tree of doooom -
https://github.com/kubernetes/kubernetes/issues/43246#issuecomment-291532473

**Comment by sjug** [comment]
@timothysc even with your solution I'm still seeing errors around containernetworking, specifically:

```
# github.com/kubernetes/perf-tests/clusterloader/vendor/github.com/containernetworking/cni/pkg/invoke
vendor/github.com/containernetworking/cni/pkg/invoke/exec.go:64: cannot use "github.com/containernetworking/cni/pkg/types".Result as type "github.com/kubernetes/perf-tests/clusterloader/vendor/github.com/containernetworking/cni/pkg/types".Result in return argument:
        "github.com/containernetworking/cni/pkg/types".Result does not implement "github.com/kubernetes/perf-tests/clusterloader/vendor/github.com/containernetworking/cni/pkg/types".Result (wrong type for GetAsVersion method)
                have GetAsVersion(string) ("github.com/containernetworking/cni/pkg/types".Result, error)
                want GetAsVersion(string) ("github.com/kubernetes/perf-tests/clusterloader/vendor/github.com/containernetworking/cni/pkg/types".Result, error)
```

**Comment by gmarek** [comment]
@sjug - after @wojtek-t fixes it seems that godep issue is gone. The thing that's wrong now is a failing test.

**Comment by gmarek** [comment]
Oh, sorry - actually now I see that you treat cluster-loader test as an unit test, which is wrong because we assume that unit tests can be run by travis (which is not true for clusterloader). Please refactor the code, so that it'll be run main binary (somehow) by some script (similarly to what we do in `kubernetes/test`)

**Comment by wojtek-t** [comment]
> Oh, sorry - actually now I see that you treat cluster-loader test as an unit test, which is wrong because we assume that unit tests can be run by travis (which is not true for clusterloader). Please refactor the code, so that it'll be run main binary (somehow) by some script (similarly to what we do in kubernetes/test)

Actually, this is exactly the same mechanim we are using in main repo (e2e.go and e2e_test.go). We just shouldn't run it with Travis.

**Comment by wojtek-t** [comment]
I will send a PR to fix this within next few minutes.
