### ISSUE TITLE
Direct Scheduler throughput e2e test-suite

### ISSUE THREAD

**Issue by hakuna-matatah** [kubernetes/perf-tests#2681]
**What would you like to be added**:
We need a test suite for measuring direct scheduler throughput without depending on KCM QPS limits.

**Why is this needed**:
- Today our load test only tests scheduler-throughput at a a very small scale i.e max-pods to 5k and also its limited by KCM throughput as current test-suite depends on deployment/replicaset controller throughput in creating pods. That would limit us from knowing the actual scheduler throughput that we can achieve out of scheduler today. 

- Also, some users of K8s today actually leverage scheduler directly to create pods without having to depend on KCM for other wrappers like deployments/jobs/replicaset controllers, we need a test-suite that would help us know the limits of scheduler throughput without having to depend on the KCM bottlenecks/regressions.
-  We could use this test-suite to run periodically in test-infra to see if we truly regress w.r.t max scheduler throughput in our e2e tests.

**Comment by hakuna-matatah** [comment]
I discussed this in Sig-scalability meeting [here](https://docs.google.com/document/d/1hEpf25qifVWztaeZPFmjNiJvPo-5JX1z0LSvvVY5G2g/edit#bookmark=kix.nrmkrgchj5bw) and got consensu

Post the sig-scalability discussion, it also appears there is need for scheduler throughput regressions from sig-scheduling folks, for context here - https://kubernetes.slack.com/archives/C09QZTRH7/p1715262959575039 

/cc @wojtek-t @marseel

**Comment by mengqiy** [comment]
Closed by https://github.com/kubernetes/perf-tests/pull/2682
/close
