### ISSUE TITLE
ClusterLoader: Investigate kube-controller-manager cpu usage

### ISSUE THREAD

**Issue by krzysied** [kubernetes/perf-tests#326]
Kube-controller-manager uses more cpu than it should. Limit is 0.8 core, however it happens that it uses ~0.9.

When this is issue is solved, clusterloader density test  kube-controller-manager constraint should be updated or at least comment explaining the reason should be added.

**Comment by krzysied** [comment]
I tried to investigated the reason of the difference. I looks like it started after fixing the pod startup time.
After seeing cpu usage over time for kube controller manger, it looks like mostly cpu is used during latency pod creation. What's more the more pods are added, the more cpu is used. I also observed ~15% difference in cpu usage between 100th and 500th latency pod creation.

I'm guessing this could be result of having 500 latency pods instead of 5x100 pods. If in original tests the cpu usage peek was for 100th latency pod at 0.8 cpu, here we can  have 0.9 at 500th latency pod. This  corresponds to 15% difference I observed.

**Comment by krzysied** [comment]
I run 5x100 and 1x500 tests three times. I've got 0.37 cpu (5x100) and 0.43 (1x500) average for create latency pods phase. It looks like 15% theory is correct.
I've also spotted increased cpu usage during saturation pods creation. However, this part is exactly like in original test, so I'm not expecting the issue to be there.

**Comment by wojtek-t** [comment]
Sorry - just clarification question. If you have 0.37 or 0.43, why do we have 0.9?

**Comment by krzysied** [comment]
0.9 happens rarely. We could change constraint, but then it will flake.
I couldn't recreate this issue on my cluster. The values I observed were mostly below 0.6.

The only difference between my test and clusterloader ci job is that I tested it on already existing cluster. I didn't tear it down and recreate it for each run. So maybe this cause the difference?

**Comment by wojtek-t** [comment]
I'm just surprised that it's even higher. IIRC, in the past those values of 0.7+ were happening when density test was run second. Here we always run density first. So it should be lower.
I buy the argument of 1x500 vs 5x100 that makes it a bit higher, but the difference shouldn't be that huge.
