### ISSUE TITLE
CLusterLoader: DNS is using more memory than it used to

### ISSUE THREAD

**Issue by krzysied** [kubernetes/perf-tests#371]
After changing tests to clusterloader's, coreDNS (and also kubeDNS) is using more memory than it used to.
![coredns_memory](https://user-images.githubusercontent.com/25119199/51028390-8e1aaf00-1593-11e9-987b-e9d73d27aaea.png)

This issue causes cordns on  5k nodes to OOM.

**Comment by krzysied** [comment]
The two biggest difference in api calls:
![endpotins_put](https://user-images.githubusercontent.com/25119199/51028757-ae973900-1594-11e9-8b44-2bfff8e2d3d9.png)
![pods_post](https://user-images.githubusercontent.com/25119199/51028762-b1922980-1594-11e9-8849-dfb50b0f419b.png)

**Comment by krzysied** [comment]
During few last days I verified, that:
- using patch instead scale doesn't have impact on metrics mentioned above.
- Reducing number of created pods should reduce the number of endpoints calls, however I don't expect this change to be big.

**Comment by krzysied** [comment]
I think I found the cause: https://github.com/kubernetes/kubernetes/blob/33a9c6e892f69e20be9527ba00bd33dfa5de221b/test/e2e/scalability/load.go#L602
In original load test, the service has additional label that is used as a selector. This label points to one specific RC. In theory every two RC should use one SVC, however it looks like every second RC uses SVC.

In clusterloader implementation, every RC is connected to some SVC, therefore it created twice as many connection as in original test.

**Comment by krzysied** [comment]
I've run some tests svc implemented as it is on original tests (svc connected to every second rc). The memory used by coredns dropped to ~11468800, which is the same amount as original tests used. Without this change coredns consumes ~14831616.

**Comment by krzysied** [comment]
/cc @wojtek-t @mborsz 
I created #374 to see if it reducing number of endpoints will fix the issue.

**Comment by krzysied** [comment]
Here's impact of #374:
![coredns_memory_change](https://user-images.githubusercontent.com/25119199/51105535-82282a80-17e9-11e9-9a9d-16c053bfb889.png)
![2k_coredns_memory_change](https://user-images.githubusercontent.com/25119199/51105634-d29f8800-17e9-11e9-965f-cdc013746646.png)
It looks like increased number of endpoints was the main issue.

**Comment by wojtek-t** [comment]
Fixed now.
