### ISSUE TITLE
ClusterLoader: Move overrides to separate directory

### ISSUE THREAD

**Issue by krzysied** [kubernetes/perf-tests#378]
Overrides should be moved from clusterloader2/testing/density/ to clusterloader2/overrides.
Overrides should be split into provider category.

**Comment by krzysied** [comment]
This will be done in 3 steps due to clusterloader code and jobs definition being in different  repos:
- [ ] copying overrides to `overrides` directory - #379 
- [ ] changing jobs, so they use new overrides
- [ ] removing old overrides

**Comment by wojtek-t** [comment]
As discussed offline - it's not clear to me it should be done this way.
Splitting overwrites between density and load/ directories makes the directory for a given test more self-contained.

There is a trade-off here, which I'm not convinced has an obvious solution. I would leave as is, until we have more evidence that one or the other approach is better.

**Comment by wojtek-t** [comment]
Given that we're fine with what we have now, I'm closing this one.
