### ISSUE TITLE
clusterload2: flag redefined: log_dir

### ISSUE THREAD

**Issue by mivanovvs** [kubernetes/perf-tests#390]
Hi there! The issue I've got on mac os and ubuntu 18.04 with GO 1.11
After all installed dependencies I've got the error:

`./run-e2e.sh
./clusterloader flag redefined: log_dir
panic: ./clusterloader flag redefined: log_dir

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc0000ba180, 0x22e92e0, 0xc00034b800, 0x215c5e8, 0x7, 0x21909df, 0x2f)
	/usr/local/opt/go/libexec/src/flag/flag.go:805 +0x529
flag.(*FlagSet).StringVar(0xc0000ba180, 0xc00034b800, 0x215c5e8, 0x7, 0x0, 0x0, 0x21909df, 0x2f)
	/usr/local/opt/go/libexec/src/flag/flag.go:708 +0x8a
flag.(*FlagSet).String(0xc0000ba180, 0x215c5e8, 0x7, 0x0, 0x0, 0x21909df, 0x2f, 0xc00034b7f0)
	/usr/local/opt/go/libexec/src/flag/flag.go:721 +0x8b
flag.String(0x215c5e8, 0x7, 0x0, 0x0, 0x21909df, 0x2f, 0xe)
	/usr/local/opt/go/libexec/src/flag/flag.go:728 +0x69`

Any ideas how to solve that?

**Comment by krzysied** [comment]
@mivanovvs I don't see this error in my local tests (I tested go 1.11.1 and 1.11.2) neither in scalability tests. Could you provide some more info, please? Are you using head version of the repository? Did you used `./run-e2e/sh` from clusterloader2 directory?

> After all installed dependencies 

What do you mean by installing dependencies? Assuming that there is existing `vendor/`, are there any dependencies missing?

**Comment by mivanovvs** [comment]
@krzysied I tested Go 1.11 on Mac os. Yes, I started with ./run-e2e.sh from clusterloader2 dir. And I use head of repository. Regarding dependencies, yes with first time run I've got a several dependencies something like 
''could not found k8s.io/perf-tests/clusterloader2/pkg/framework"
"k8s.io/perf-tests/clusterloader2/pkg/flags"
"k8s.io/perf-tests/clusterloader2/pkg/measurement/common/bundle"
"k8s.io/kubernetes/pkg/util/logs"
"k8s.io/apimachinery/pkg/labels"

**Comment by mivanovvs** [comment]
Thanks. It fixed issues with dependencies. But I've got error

> F0129 12:36:12.891777   48456 clusterloader.go:159] Parsing flags error: [no test config path specified]

**Comment by krzysied** [comment]
The error comes from https://github.com/kubernetes/perf-tests/blob/4ef9777fdcc1473907cff936ca3d5827d0f80bfd/clusterloader2/cmd/clusterloader.go#L77
There is a required flag `testconfig`. For example you can try "`--testconfig=./testing/load/config.yaml`"

You can think of "`./run-e2e.sh`" as a alias for "`go run cmd/clusterloader.go --kubeconfig=${HOME}/.kube/config`".

[README](https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/README.md) can be not up-to-date, however flags section should be ok.

**Comment by krzysied** [comment]
@mivanovvs Is this issue still valid?

**Comment by mivanovvs** [comment]
@krzysied hi! nope, issue has been fixed. Many thanks for help!
