### ISSUE TITLE
ClusterLoader2 assumes ssh service should be available

### ISSUE THREAD

**Issue by Betula-L** [kubernetes/perf-tests#396]
**What happened?**

In our cluster, ssh is not available. However, `clusterloader2/pkg/measurement/util/ssh.go:88` assumes every master should own an available ssh service. 

Errors occurred as follow, 

```
[root@Betula-L kubernetes]# ./clusterloader --kubeconfig="${HOME}/.kube/config" --testconfig=testing/density/config.yaml --provider=kubemark --masterip=10.142.43.51 --mastername=localhost
E0201 11:30:17.948014   11090 test_metrics.go:127] TestMetrics: [unexpected error (code: 0) in ssh connection to master: &errors.errorString{s:"error getting signer for provider kubemark: 'error reading SSH key /root/.ssh/google_compute_engine: 'open /root/.ssh/google_compute_engine: no such file or directory''"}]
E0201 11:30:17.948183   11090 kubemark.go:50] error when trying to SSH to master machine. Skipping probe. error getting signer for provider kubemark: 'error reading SSH key /root/.ssh/google_compute_engine: 'open /root/.ssh/google_compute_engine: no such file or directory''

```
**What you expected to happen**:

We may run clusterloader on master without ssh. If parameter `masterip==localhost`, clusterloader could execute `func execLocal()`  rather than `func SSH()`

**Comment by wojtek-t** [comment]
The requirement for ssh is limiting (I agree), but it should break your test.
If anything is failing due to that reason, then we should fix that.

Otherwise (if these are only error lines in the log file), you can probably ignore them.

@krzysied

**Comment by wojtek-t** [comment]
> I think it's hard to be ignore. i can't acquire most of results if errors occurred.

The most crucial one (e.g. those validating SLOs, etc.) should be available.
Those "auxiliary" ones (like profiles, etc.) won't be, which is kind of expected.

I guess I'm trying to set expectations right.
Also, running tests on your master machine is really bad idea due to resource consumption of the tests itself.

**Comment by Betula-L** [comment]
@wojtek-t , could provider `kubemark` acquire SSH_KEY_FILE from env `KUBEMARK_SSH_KEY` rather than constant string `google_compute_engine`? 
```
case "kubemark":
  keyfile = os.Getenv("KUBEMARK_SSH_KEY")
  if len(keyfile) == 0 {
  	keyfile = "google_compute_engine"
  }
```
https://github.com/kubernetes/perf-tests/blob/6c738e30dc1277abf7ae8c069a6d3b62b78d1703/clusterloader2/pkg/measurement/util/ssh.go#L85

**Comment by Betula-L** [comment]
Why not those ssh key configs use the same environment variable, such as "CLUSTERLOAD_SSH_KEY".

**Comment by wojtek-t** [comment]
> @wojtek-t , could provider `kubemark` acquire SSH_KEY_FILE from env `KUBEMARK_SSH_KEY` rather than constant string `google_compute_engine`?

SGTM - feel free to change that, I'm happy to review this.
