### ISSUE TITLE
ClusterLoader2 should support controllers beside ReplicationController

### ISSUE THREAD

**Issue by Betula-L** [kubernetes/perf-tests#414]
**What would you like to be added**:
1. Add parameter `apiVersion` for `type waitForControlledPodsRunningMeasurement struct `
2. Support measurement`WaitForControlledPodsRunning` for kinds in different apiVersions (different controllers)

**Why is this needed**:

**Kubernetes e2e test:** Kubernetes supports multiple controllers such as Deployment, Job, ReplicationController, etc. For kubernetes/kubernetes density test, all of them are supported.

https://github.com/kubernetes/kubernetes/blob/2b9c9154b52bdac914bf3ab37c8d349d926e6e16/test/e2e/scalability/density.go#L557

**ClusterLoad2:**  Clusterload2 only support controllers in CoreV1. Controllers `Deployment`, `Job`, etc. can't be measured by clusterload2.  

 Clusterload2 does not provides parameter `apiVersion` for measurement `WaitForControlledPodsRunning`, due to codes as followed, it can't create listwatch expect in CoreV1().

https://github.com/kubernetes/perf-tests/blob/74aa0691d943234621454aab72c180d4648f9ee6/clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go#L155

**Comment by wojtek-t** [comment]
Great point.

@krzysied - please fix

**Comment by krzysied** [comment]
- [ ] Hot fix #415 
Fixing ReplicaSet, Deployment, DaemonSet and Job handling.
- [ ] Replacing clientset with dynamic clent.
This will allow more generic handling.

**Comment by wojtek-t** [comment]
I actually claim that it's not that urgent to make a hack to fix it.
We should wait for a proper fix.

**Comment by Betula-L** [comment]
This is fixed in https://github.com/kubernetes/perf-tests/pull/438
