### ISSUE TITLE
100th percentile of pod-startup-latency is reported as 0 in perf-dash

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/perf-tests#422]
![vqrcaed2dpa](https://user-images.githubusercontent.com/2604887/53244974-b4605e00-36ac-11e9-962c-5174b7a9de4b.png)

**Comment by krzysied** [comment]
In original test pod startup latency had values for 50th. 90th, 99th and 100th percentile. Cluster loader version has values only for 50th, 90th and 99th perc.
The gce 5000 ci job was migrated to cluster loader between 308 and 309 run: https://github.com/kubernetes/test-infra/pull/11282/

The decision to drop 100th percentile was made to unified metric look. Other metrics (apiserver responsiveness, resource usage, schdeuling latancy) provide 50th, 90th and 99th percentile.

**Comment by mm4tt** [comment]
Sg, thanks @krzysied for explanation!

/close
