### ISSUE TITLE
clusterloader uses godep now obselete

### ISSUE THREAD

**Issue by rus4** [kubernetes/perf-tests#437]
so i am trying to use clusterloader but it seems it requires godep which is now obselete ( february 2019 ), is there any plans to move to dep , or any info on how to make this work now that godep is no longer available on ubuntu.

**Comment by wojtek-t** [comment]
clusterloader is now deprecated - you can use clusterloader2:
https://github.com/kubernetes/perf-tests/tree/master/clusterloader2

**Comment by rus4** [comment]
thanks for this , so for clusterloader2 i have used the default config yaml for load test an generated my own kubernetes config yaml by running `kubectl -n kube-system get cm kubeadm-config -o yaml`
providing these configs to clusterloader2 it runs but is looking for master node ip & name an throws a ssh error however i am getting further than what i did with clusterloader , my output is here: 
`I0228 13:05:03.187613   21774 simple_test_executor.go:342] Resources cleanup time: 33.642µs
E0228 13:05:03.187640   21774 clusterloader.go:145] --------------------------------------------------------------------------------
E0228 13:05:03.187647   21774 clusterloader.go:146] Test Finished

E0228 13:05:03.187653   21774 clusterloader.go:147]   Test: config.yaml

E0228 13:05:03.187656   21774 clusterloader.go:148]   Status: Fail

E0228 13:05:03.187659   21774 clusterloader.go:150]   Errors: [measurement call TestMetrics - TestMetrics error: [unexpected error (code: 0) in ssh connection to master: &errors.errorString{s:"error getting signer for provider : 'GetSigner(...) not implemented for '"}]
measurement call TestMetrics - TestMetrics error: [unexpected error (code: 0) in ssh connection to master: &errors.errorString{s:"error getting signer for provider : 'GetSigner(...) not implemented for '"}
unexpected error (code: 0) in ssh connection to master: &errors.errorString{s:"error getting signer for provider : 'GetSigner(...) not implemented for '"}

failed to execute curl command on master through SSH: error getting signer for provider : 'GetSigner(...) not implemented for '

failed to execute curl command on master through SSH: error getting signer for provider : 'GetSigner(...) not implemented for '

failed to execute curl command on master through SSH: error getting signer for provider : 'GetSigner(...) not implemented for ']]
E0228 13:05:03.187672   21774 clusterloader.go:152] --------------------------------------------------------------------------------
F0228 13:05:03.187831   21774 clusterloader.go:225] 1 tests have failed!
`


I have done some digging into this issue an it seems others are having similar experiences with SSH like these here: 
https://github.com/kubernetes/perf-tests/issues/396
https://github.com/kubernetes/perf-tests/issues/385

although not sure about the name & ip thing going on maybe that will clear once ssh issue is sorted.

**Comment by wojtek-t** [comment]
@krzysied - can you help with that?

**Comment by krzysied** [comment]
@rus4 My guess is there should be provider flag added for test run command.
Add "--provider=\<p\>" where \<p\> is one from https://github.com/kubernetes/perf-tests/blob/6274cc527a10d49925b01ad8181d889af1a54fef/clusterloader2/pkg/measurement/util/ssh.go#L85

**Comment by treetopbet** [comment]
@krzysied thanks so I need to give the flag for my private key for ssh stuff it seems dont get a choice for not using ssh ( we have to use it - ha ha) is fine I just need to spend bit more time sorting it all out.
Thanks again for replying.

**Comment by rus4** [comment]
@krzysied so I need to give the flag for my private key for ssh stuff it seems cannot opt-out from using ssh ( we have to use it - ha ha) is fine I just need to spend bit more time sorting it all out.
Thanks again for replying.

**Comment by wojtek-t** [comment]
clusterloader code has been removed :)
