### ISSUE TITLE
Clusterloader2 SSH an connection timeouts retries and INTERNAL_ERROR

### ISSUE THREAD

**Issue by rus4** [kubernetes/perf-tests#451]
I seem to be getting a recurring issue when running clusterloader2 on-prem using ubuntu OS and using the skeleton providor, I am passing the master name an ip when running the load test ,on the load test runs I keep seeing messages like this:

`E0311 14:37:00.777610    3243 streamwatcher.go:109] Unable to decode an event from the watch stream: stream error: stream ID 387; INTERNAL_ERROR
E0311 14:38:00.917035    3243 streamwatcher.go:109] Unable to decode an event from the watch stream: stream error: stream ID 403; INTERNAL_ERROR
W0311 14:38:00.917164    3243 reflector.go:303] k8s.io/perf-tests/clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go:203: watch of <nil> ended with: very short watch: k8s.io/perf-tests/clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go:203: Unexpected watch close - watch lasted less than a second and no items received
error dialing rus4@172.16.20.18:22: 'dial tcp 172.16.20.18:22: connect: connection timed out', retrying
E0311 14:39:02.204236    3243 streamwatcher.go:109] Unable to decode an event from the watch stream: stream error: stream ID 407; INTERNAL_ERROR
W0311 14:39:02.204276    3243 reflector.go:303] k8s.io/perf-tests/clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go:203: watch of <nil> ended with: very short watch: k8s.io/perf-tests/clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go:203: Unexpected watch close - watch lasted less than a second and no items received
E0311 14:40:03.492289    3243 streamwatcher.go:109] Unable to decode an event from the watch stream: stream error: stream ID 411; INTERNAL_ERROR`

Can anyone verify if on-prem is supported fully? or any ideas what might be wrong?

**Comment by wojtek-t** [comment]
What is "skeleton provider"?

Also, the errors that you pasted doesn't seem to depend on the provider - we simply can't establish watch, which shouldn't depend on the cluster provider at all.
