### ISSUE TITLE
ClusterLoader: Unsafe prometheus getKubemarkMasterClusterIp

### ISSUE THREAD

**Issue by krzysied** [kubernetes/perf-tests#459]
There is a problem with flaking kubemark tests.

IIUC the problem is caused by https://github.com/kubernetes/perf-tests/blob/38cd4ef9bff2646f63690b6137a70a3705e5148b/clusterloader2/pkg/prometheus/prometheus.go#L274
The requirement for this bug to happen is for example having two kubemark clusters within one project. The instance list will return two ip addresses, which generates bad manifest yaml.
I'm also guessing that naming cluster "...-kubemark" will result in having instances "...-kubemark-master" and "...-kubemark-kubemark-master". Both instances will satisfy the command filter. 

getKubemarkMasterClusterIp should be implemented in a different way.

ref https://github.com/kubernetes/kubernetes/issues/73105

**Comment by mm4tt** [comment]
/assign

Thanks @krzysied, will take a look.

**Comment by mm4tt** [comment]
/close
Fixed by https://github.com/kubernetes/perf-tests/pull/465
