### ISSUE TITLE
Perfdash displays only one result per ci job

### ISSUE THREAD

**Issue by krzysied** [kubernetes/perf-tests#469]
Perfdash displays only one result with weird number for each ci job.

**Comment by krzysied** [comment]
It seems the problem what cause by the changes in run ids - https://github.com/kubernetes/test-infra/issues/9604. Perfdash assumes that build ids are sequential.

**Comment by krzysied** [comment]
Perfdash uses k8s.io/contrib/test-utils/utils/utils.go to access the logs. It iterates over decreasing sequence of numbers starting from the latest build id (latest-build.txt)

**Comment by krzysied** [comment]
- [ ] Adding build number listing for given ci job https://github.com/kubernetes/contrib/pull/3005
- [ ] Updating vendor with contrib changes
- [ ] Changing perfdash logic to fetch logs based on listed build numbers

**Comment by wojtek-t** [comment]
@krzysied - this has been fixed, right?

**Comment by krzysied** [comment]
Perfdash is working. There were some changes in vendor. I still need to push them to contrib repo.
Let's keep this issue open.
