### ISSUE TITLE
There is exactly one profile for each (component, test, profile type) tuple

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/perf-tests#489]
https://github.com/kubernetes/perf-tests/pull/478 changes profile gathering to be periodic.
However, we still seem to have exactly one profile.

I think that the reason is how we report the summaries at the end of the test:
https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/pkg/test/simple_test_executor.go#L87

Basically what happens is that we name the file according to:
SummaryName(), confg.Name and current_time
which means that given all profiles has the same name, they will be overwriting one another.

I think the right solution to that is to:
- extend Summary type with `timestamp` and `extension` field (I would like profiles to be `.raw` ones)
- set that in profile gathering
- when reporting, use fields from summary and if empty default as currently

@krzysied - FYI

**Comment by krzysied** [comment]
> extend Summary type with timestamp and extension field (I would like profiles to be .raw ones)

+1 It will be also required when there are api responsiveness and api responsiveness prometheus measurements enabled in one test.

**Comment by wojtek-t** [comment]
> +1 It will be also required when there are api responsiveness and api responsiveness prometheus measurements enabled in one test.

I'm not convinced about this one - those technically will be different measurements (at least initially), I think.

**Comment by wojtek-t** [comment]
This has been fixed in the meantime.
