### ISSUE TITLE
Testing api responsiveness prometheus measurement

### ISSUE THREAD

**Issue by krzysied** [kubernetes/perf-tests#498]
- Comparing api responsiveness prometheus measurement vs api responsiveness measurement.
  - Api responsiveness prometheus measurement should be enabled in density and load test.
  - Api responsiveness prometheus measurement should not cause test to fail.
- After tests are done api responsiveness prometheus measurement should be changed to test-failing.

**Comment by oxddr** [comment]
It seems that Prometheus-based metrics has been enable for quite some time. What are criteria for switching measurements of API calls latency to Prometheus exclusively?

**Comment by oxddr** [comment]
After offline discussion with @krzysied, it seems that there is discrepancy between old (apiserver-based) and new (Prometheus-based) calculations and the newer one being more strict. It seems however that the Prometheus-based approach is closer to definition of SLO.

**Comment by wojtek-t** [comment]
They are "kind-of" more strict, they are different. But yes - they reflect the SLO and we want to start using them.

**Comment by oxddr** [comment]
The old measurement has been replaced by the one using newer metric. 

/close
