### ISSUE TITLE
Migrate kubernetes/perf-tests out of Travis

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/perf-tests#552]
See the [Prow will not able to check Travis context as Travis migrating off old status context API](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-dev/z4yDUNMyW_0/hpxKGzDnBAAJ) announcement for context.

It will still somehow work, as tide is configured to honor statuses it does not know about, so if it finds a failing Travis context it will not want to merge until it notices no failing context. 
It's possible though, that it will merge a PR without Travis context. Also a race condition where travis restarted is possible.

Till now, we've found only one example where PR was merged with red Travis status - https://github.com/kubernetes/perf-tests/pull/534

It's not a critical urgent priority, but we should address it.

A straightforward solution would be to migrate Travis checks to Prow jobs.

**Comment by mm4tt** [comment]
/remove-lifecycle stale
/good-first-issue
(if someone wants to learn a bit about our codebase and presubmits)

**Comment by mm4tt** [comment]
Thanks, @skurtzemann!  Also big thanks for fixing the etcd profiles!!!

@oxddr, you had some thoughts about it, right?  Let me know if I'm mistaken, if so, I'll try explaining what should be done.

**Comment by oxddr** [comment]
> janluk, you had some thoughts about it, right? Let me know if I'm mistaken, if so, I'll try explaining what should be done.

I don't recall having a specific thoughts about it. The only thing I can think of now is that we can start using `golangci-lint` instead if `gofmt` and `golint` to check the code (please see https://github.com/kubernetes/perf-tests/issues/573). In general those two check are good candidate to migrate first. There are existing images available for them (or for `golangci-lint` FWIW), so adding a new prow presubmit should be relatively easy.

**Comment by mm4tt** [comment]
Thanks, @oxddr 

@skurtzemann, please let me know if the first steps that Janek proposed are clear. Don't hesitate to ask questions if something is not

**Comment by wojtek-t** [comment]
In travis we were building everything in this repo and running unit tests. Being able to do that would be extremely useful - without it we're a bit blind.

**Comment by skurtzemann** [comment]
@mm4tt, @oxddr 
If my understanding of your issue is good : you will to migrate the `.travis.yml` content into prow jobs ?
And the first step wiil be these 2 instructions (https://github.com/kubernetes/perf-tests/blob/master/.travis.yml#L26-L27) using `golangci-lint` ?

**Comment by oxddr** [comment]
@skurtzemann, yes, your understanding is correct: we would like to move away from Travis in favor of Prow and move linters in the first step.

**Comment by skurtzemann** [comment]
@oxddr : Thanks.
Where can I start writing Prow jobs ?

**Comment by oxddr** [comment]
We run presubmits on Prow instance maintained by test-infra folks.
Configuration of our presubmits live in `kubernetes/test-infra` repository
in
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-scalability/sig-scalability-presubmit-jobs.yaml.
Linters should be added there under `perf-tests` key in yaml file.

>

**Comment by oxddr** [comment]
Done!

/close
