### ISSUE TITLE
Use golangci-lint instead of pure golint

### ISSUE THREAD

**Issue by oxddr** [kubernetes/perf-tests#573]
We could use [golangci-lint](https://github.com/golangci/golangci-lint) - linter agregator for go. It uses more linters than just golint, thus will help us more problems in the code (e.g. it uses [errcheck](https://github.com/kisielk/errcheck) to find places when code doesn't check returned error).  This should be a simple change. 

/kind cleanup 

@mborsz @mm4tt @krzysied opinions?

/assign @oxddr

**Comment by mm4tt** [comment]
Sounds great, +1

**Comment by wojtek-t** [comment]
I'm not completely against, but we need to be aware that this would mean difference with all other repos.
Maybe we still want it, but it needs to be conscious decision.

If this is much better, we may want to suggest using it in other repos too :)

**Comment by oxddr** [comment]
golangci-lint offers many checkers. It's up to us to pick which one we choose. In the first step we can enable only golint, so there won't be any change from what we have now. While some of checkers are opinionated, some are worth using beyond argument (e.g. mentioned errcheck). 

I'd enable it here first. Once we have a good case, we can then propose it to other repose under k.

**Comment by mm4tt** [comment]
This is blocked by https://github.com/kubernetes/perf-tests/issues/552, but we still want to do it.
/remove-lifecycle stale

**Comment by oxddr** [comment]
@mm4tt I've just checked locally removal of `-min_confidence=0.9` flag from golint - we have 35 outstanding issues. Please see my PR ref to this issue.

**Comment by oxddr** [comment]
/remove-lifecycle stale
golangci-lint is available as a Docker image - we could easily move the
running lint of Travis to Prow this way.

**Comment by oxddr** [comment]
Fixed!

/close
