### ISSUE TITLE
Add documentation on how to test perf-dash locally

### ISSUE THREAD

**Issue by oxddr** [kubernetes/perf-tests#585]
Especially how to test newly added parser. According to @krzysied it should be possible to configure perf-dash so it only parse last N runs. This is enough for checking whether it works as expected and has shorter feedback loop. 

/area perf-dash
/kind documentation

**Comment by wojtek-t** [comment]
@mborsz - maybe this can be done together with the adjusting of perfdash to support TestSuite?

/remove-lifecycle stale

**Comment by mborsz** [comment]
@pierewoj, I know that you managed to run perf dash locally. How did you know how to do that? Could you write down short doc with list of steps required to do so?
