### ISSUE TITLE
Figure out why presubmit didn't catch breaking scalability tests in https://github.com/kubernetes/perf-tests/pull/586

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/perf-tests#588]
@kubernetes/sig-scalability-bugs 
@mm4tt @krzysied @mborsz

**Comment by mm4tt** [comment]
My guess is that the "NetworkProgrammingLatency" is a gated feature that has to be explicitly enabled via config override and it's not enabled in presubmits. 
I guess we should enable it in presubmit once we get confidence that it works (which I think we got already).

**Comment by wojtek-t** [comment]
Makes sense - but that implies that we should never enable sth in blocking tests without enabling it in presubmits too.

**Comment by oxddr** [comment]
@wojtek-t yes, we should have enabled the experiment in the presubmit first. I'll create a short doc about how to rollout experiments in clusterloader. Hopefully with clear and explicit  instructions, we can avoid situations like that.
