### ISSUE TITLE
ClusterLoader e2e tests are not uploading artifacts

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/perf-tests#59]
I guess these might be some permission issues.

**Comment by wojtek-t** [comment]
@gmarek @sjug

**Comment by wojtek-t** [comment]
@gmarek @sjug

**Comment by gmarek** [comment]
@kubernetes/test-infra-maintainers

**Comment by krzyzacy** [comment]
where does it put artifacts to?

**Comment by wojtek-t** [comment]
@krzyzacy - I'm talking about regular artifacts from k8s cluster.

The pattern for this test is as following:
- start kubernetes cluster (as we do everywhere)
- instead of running tests from main repo, run something different
- tear down kubernetes cluster

We are missing logs from the kubernetes clusters (i.e. apiserver, scheduler, ...). I'm not talking about anything specific to our tests.

**Comment by krzyzacy** [comment]
```
0516 13:49:35.515] Warning: Permanently added 'compute.3003323207617265194' (RSA) to the list of known hosts.
W0516 13:49:35.560] Permission denied (publickey).
W0516 13:49:35.604] ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
I0516 13:49:35.704] Removing etcd replica, name: bootstrap-e2e-master, port: 2379, result: 255
W0516 13:49:36.424] Permission denied (publickey).
W0516 13:49:36.426] ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
I0516 13:49:36.526] Removing etcd replica, name: bootstrap-e2e-master, port: 4002, result: 255
```

maybe ssh issue, I'll double check prow config

**Comment by krzyzacy** [comment]
it fix the ssh but still did not have those logs... I think it's because the test did not use bootstrap-e2e-master?

**Comment by wojtek-t** [comment]
What is bootstrap-e2e-master?

**Comment by krzyzacy** [comment]
bootstrap-e2e should be the default cluster name.

logs like apiserver resides in bootstrap-e2e-master node for regular e2e jobs, like http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce/8488/artifacts/bootstrap-e2e-master/, as far as I know.. I'm not sure where the apiserver log is generated from though..
