### ISSUE TITLE
ClusterLoader2 - update (internal-)?master-ip flags and vars to plural

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/perf-tests#595]
Multi-master support was added to ClusterLoader2 in https://github.com/kubernetes/perf-tests/pull/544.

We should update the name of master-ip and internal-master-ip flags and vars to plural.

**Comment by mm4tt** [comment]
Steps:

1. Find all places in `k8s.io/test-infra` that are setting the `MASTER_IP` or `MASTER_INTERNAL_IP`, update them to also set the plural variable (`MASTER_IPS`, `MASTER_INTERNAL_IPS`)
2. Update the ClusterLoader2 code to change the names from singular to plural (`MASTER_IP` -> `MASTER_IPS`), see TODOs in https://github.com/kubernetes/perf-tests/pull/544
3. Clean up `k8s.io/test-infra` to stop setting singular name variables (if cl2 is the only binary reading that env).

**Comment by Jukie** [comment]
Do the gcloud calls return all of the needed ip's or should I be adding a loop to handle that?
https://github.com/kubernetes/test-infra/blob/ef83ebe5d17630bd608d618ae89bfec1c0f35842/kubetest/e2e.go#L606-L611
```
	masterIP, err := control.Output(exec.Command(
		"gcloud", "compute", "addresses", "describe",
		os.Getenv("MASTER_NAME")+"-ip",
		"--project="+o.gcpProject,
		"--region="+o.gcpZone[:len(o.gcpZone)-2],
		"--format=value(address)"))
```
https://github.com/kubernetes/test-infra/blob/ef83ebe5d17630bd608d618ae89bfec1c0f35842/kubetest/e2e.go#L624-L629
```
	masterInternalIP, err := control.Output(exec.Command(
		"gcloud", "compute", "instances", "describe",
		os.Getenv("MASTER_NAME"),
		"--project="+o.gcpProject,
		"--zone="+o.gcpZone,
		"--format=value(networkInterfaces[0].networkIP)"))
```

I'm mostly familiar with AWS, but I'm curious if the following needs to be modified to loop over every interface:
`"--format=value(networkInterfaces[0].networkIP)"))`

**Comment by Jukie** [comment]
- [ ] Add plural variables to k8s.io/test-infra
- [ ] Update CL2 to use the new variables
- [ ] Cleanup k8s.io/test-infra

**Comment by mm4tt** [comment]
/remove-lifecycle stale

There are WIP (but unfortunately, not active) PRs for this. If anyone else would like to take over the work here, please let me know.
