### ISSUE TITLE
Missing some files

### ISSUE THREAD

**Issue by zilman** [kubernetes/perf-tests#6]
In [dnsperf](https://github.com/kubernetes/perf-tests/tree/master/dns/dnsperf):

> Change the completions and parallelism parameters in the dnsperf-job.yaml file to increase the number of test pods.

But no such file.

In [netperf](https://github.com/kubernetes/perf-tests/tree/master/network/benchmarks/netperf) the images directory is missing so the graphics in the readme don't show up.

**Comment by gmarek** [comment]
cc @girishkalele @thockin

**Comment by gmarek** [comment]
@thockin - sorry for assigning this to you, but you have the most context here.

**Comment by thockin** [comment]
Cleanup on aisle 3.

**Comment by jeremyeder** [comment]
We have a really good set of network tests that perform similar functions.  Is this particular test set in stone?  Or is it an option for us to contribute ours?

https://github.com/openshift/svt/tree/master/networking/synthetic

**Comment by thockin** [comment]
Contributions welcome
