### ISSUE TITLE
Migrate perf-dash off debian

### ISSUE THREAD

**Issue by oxddr** [kubernetes/perf-tests#604]
Perf-dash uses debian at the moment. We could try to migrate it to scratch or busybox. 

/area perf-dash

**Comment by wojtek-t** [comment]
We should migrate to distroless.

/remove-lifecycle stale

**Comment by skurtzemann** [comment]
Hi @oxddr, 
I'll like to get this issue and I had some questions ;)

- can we perharps include the `go build` process into the `Dockerfile` as a build stage instead of copying the binary into the `Dockerfile`
- what version of golang do you use to build `perf-dash`
- how can i plugs data into `perf-dash` to test it ?

Thanks

**Comment by oxddr** [comment]
Awesome!

> * can we perharps include the `go build` process into the `Dockerfile` as a build stage instead of copying the binary into the `Dockerfile` ?

Sure, that's a good idea to make builds more reproducible. 

> * what version of golang do you use to build `perf-dash` ?

I've used go1.14 last time. I'd use whichever is the newest and works with the codebase. We don't have specific requirements around this as long as perf-dash works.

> * how can i plugs data into `perf-dash` to test it ?

Please have a look at `Makefile` and `run` target. It loads actual test data for few recent builds (you may want to decrease this number even more to speed things up). 

Please let me know if you have any other questions.

**Comment by skurtzemann** [comment]
Thanks for your response.

Inside the `golang:1.14.1` I've got the following error after launch `make run` :

```
E0331 15:44:41.418705   12067 google-gcs-downloader.go:138] Error while looking for artifacts/in_cluster_network_latency_load* in ci-kubernetes-kubemark-500-gce-stable2 build 1244640772502851585: <nil>
```

**Comment by oxddr** [comment]
AFAIK this is expected. perf-dash lookups cartesian product of {jobs, log files}, so it won't be able to find some of them. Error messages around it can be misleading it seems.

**Comment by skurtzemann** [comment]
> AFAIK this is expected. perf-dash lookups cartesian product of {jobs, log files}, so it won't be able to find some of them. Error messages around it can be misleading it seems.

With these errors the dashboard will still display some data ?

**Comment by oxddr** [comment]
Most of the time, this is expected. If you want to verify, data was loaded correctly, check some of the graphs (e.g. API responsivess or compare to perf-dash.k8s.io) . As mentioned earlier, those log statements are misleading.

**Comment by wojtek-t** [comment]
@shyamjvs - will you or someone on your side be able to help with it? We are periodically facing vulnerabilities with debian image and it would be good to finally get rid of it.
