### ISSUE TITLE
Make it possible to source yamls in yamls

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/perf-tests#619]
I'm wondering how much work would it be allow injecting yamls to other yamls.

I've been thinking about it for some time, but https://github.com/kubernetes/perf-tests/pull/601 is actually a good example.
Would it be possible to define your yaml as:
```
// here is my yaml
{{ .sourceFrom someFile }}

@mm4tt @krzysied

**Comment by mm4tt** [comment]
This is already possible, e.g. see - https://github.com/kubernetes/perf-tests/blob/6b699a104fa2378996711bacc1a2d172f8548cd5/clusterloader2/pkg/prometheus/manifests/grafana-dashboardDefinitions.yaml#L10

**Comment by wojtek-t** [comment]
Nice - I didn't know about it.
