### ISSUE TITLE
ClusterLoading CI test failing

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/perf-tests#62]
PR https://github.com/kubernetes/perf-tests/pull/55 broke it:

```
Error parsing config, open content/pod-pause.json: no such file or directory
```

cc @sjug @wojtek-t

**Comment by sjug** [comment]
It's referencing `${clusterloader_dir}/content/pod-pause.json` which exists in the git repo [here](https://github.com/kubernetes/perf-tests/blob/master/clusterloader/content/pod-pause.json).
