### ISSUE TITLE
Network Programming Latency: investigate spikes

### ISSUE THREAD

**Issue by oxddr** [kubernetes/perf-tests#640]
http://perf-dash.k8s.io/#/?jobname=gce-100Nodes&metriccategoryname=KubeProxy&metricname=NetworkProgrammingLatency

![asd](https://user-images.githubusercontent.com/30298753/61291559-1a21c380-a7cf-11e9-9087-05a4769acd24.png)

/assign @oxddr

**Comment by oxddr** [comment]
/reopen 

While there is a visible improvement in gce5000, I still see spikes in gce100. 

![vOKXReNvre7](https://user-images.githubusercontent.com/30298753/63263084-eaf7e980-c287-11e9-8a50-897e48ea79ec.png)

**Comment by oxddr** [comment]
root cause: kube-proxy doesn't distinguish between cache sync and add/update events when exporting "network programming latency" metric. 

I had a look at [this run](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1165928760730456064), which has very high 99th percentile of network programming latency. kube-proxy on at least one node has been restarted during the test. When restarted, kube-proxy listed all services and exported network programming latency for them. Because all of the services were updated long time ago (~38 ago for prometheus-k8s service), the network programming latency values were very high.

**Comment by oxddr** [comment]
@wojtek-t: I haven't look into that, I'll do that tomorrow. The whole test suite has passed FWIW. 

Anyway, we should make SLI calculations immune to component restarts.

**Comment by oxddr** [comment]
99th percentile is rather a weak protection. An example: if there is larger number of service in the cluster with low churn, this won't protect us. I think the investigation of this particular failure is independent from whether we want to include or not sync events. I'll have a look at it anyway, but of we intend to take sync into account restarts, we should be somehow explicit about it and if not, we should not measure them (my PR mentioned above aims at doing so).

**Comment by oxddr** [comment]
I had exactly this interpretation in mind, apologize for being clear. This indirectly incorporate node-uptime into networking programming latency and I am not convinced it should be taken into account. I've checked the [wording of this SLI](https://github.com/kubernetes/community/blob/master/sig-scalability/slos/network_programming_latency.md) and it's unclear on this aspect too.

**Comment by oxddr** [comment]
I had a look at the node and it was targeted by NodeKiller, so business as usual. This also explains why we see spikes in gce100, but not gce5000 where NodeKiller is not enabled.

**Comment by oxddr** [comment]
Two nodes has been restarted during the test ~25 minutes apart from each other.

**Comment by wojtek-t** [comment]
FYI - this issues may be related:
https://github.com/kubernetes/kubernetes/issues/82364

**Comment by oxddr** [comment]
Closing this one in favor of https://github.com/kubernetes/kubernetes/issues/82364
