### ISSUE TITLE
Don't use raw pods in storage experimental tests

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/perf-tests#666]
Forked from https://github.com/kubernetes/perf-tests/pull/662

@wojtek-t : I'm fine with it as a starting phase, but we should move them to use deployments (using individual pods is more like anti-pattern, and startup-time is measured from pod creation anyway, so it shouldn't cause any additional problems).

@mucahitkurt : When I use a controller like deployments I can't control the volume names of the pod that controller creates.

I tried it with statefulset, for replication number 2, statefulset creates pod likes app-0-pod-0, app-0-pod-1, if I want to use volumes with these pod I should create volumes likes pod-0-vol-0, pod-0-vol-1, pod-1-vol-0, pod-1-vol-1. But I can't create volume names like 2 indexed values for pod-[podIndex]-vol-[volumeIndex], because clusterloader2 framework doesn't allow this.

I know that it's an anti-pattern working directly with the pods without a controller, but I couldn't solve the above problem and used directly pod.

**Comment by wojtek-t** [comment]
> When I use a controller like deployments I can't control the volume names of the pod that controller creates

@mucahitkurt - I think I don't fully understand it.
What I was suggesting is that instead of creating N pods, create N deployments, with 1 pod each.
Given that deployment contains PodSpec which is exactly the same as PodSpec in Pod, you should basically be able to do exactly the same in both cases.

What am I missing?

**Comment by mucahitkurt** [comment]
@wojtek-t when I use N deployments instead of N pods there should't be problem, I thought/tried replication properties of the controller to create N pods with one deployment. I thought creating N deployments is not meaningful

I'll try it and will change existing test cases.

**Comment by wojtek-t** [comment]
@mucahitkurt - sorry, I guess I wasn't clear. I had N deployments on my mind since the early beginning - otherwise we don't control speed of creation, etc.
