### ISSUE TITLE
Expose pod-startup-time metrics for newly added storage tests in perf-dash

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/perf-tests#669]
@krzysied - do we finally have a description how to do that? Can you please help with it?

**Comment by oxddr** [comment]
I have a PR in-progress that adds documentation on this very topic. It was low on my list so far though. Shall I prioritize it?

**Comment by wojtek-t** [comment]
> Shall I prioritize it?

It's lower priority than SLI-related stuff you're working on. So no.

@krzysied - can you please help with setting them up - I guess it will be O(10) lines of code (+release, which people from community can't do anyway).

**Comment by oxddr** [comment]
I have another issue opened purely for adding the documentation: https://github.com/kubernetes/perf-tests/issues/589. Assigning to @krzysied to update and release perf-dash

/assign @krzysied

**Comment by krzysied** [comment]
Perfdash is updated.
Can we close the issue?

**Comment by wojtek-t** [comment]
Yes - thanks.
