### ISSUE TITLE
Setup mungers for this repo

### ISSUE THREAD

**Issue by gmarek** [kubernetes/perf-tests#7]
We need a couple of mungers running in this repo:
- CLA bot
- build/gofmt/golint bot
- unit test bot (we'll probably have some unit tests for frameworks here)

cc @kubernetes/sig-scalability @apelisse

**Comment by apelisse** [comment]
I've seen this. Of all these tasks, mungebot would only take care of CLA (and we're wondering how this will scale across many differents repos with @foxish).

I would recommend using travis for the second and maybe third bullet points, but cc @kubernetes/sig-testing that may have a different opinion

**Comment by gmarek** [comment]
@apelisse thanks for the info. Please let me know as soon as you know if CLA bot will be able to take care of this repo.

I'm completely unfamiliar with setting up travis on repos - do you have any pointers?

**Comment by spxtr** [comment]
Travis is pretty simple to set up. You can take a look at test-infra's [.travis.yml](https://github.com/kubernetes/test-infra/blob/master/.travis.yml), but that's mostly for python code.

If you want easy integration with the rest of our tools you can look into adding your repo to [this file](https://github.com/kubernetes/test-infra/blob/master/ciongke/jobs.yaml) along with a Jenkins job that looks similar to [this](https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins-pull/testinfra-pull.yaml). It's a bit of a hassle, but you'll get nice things along with it.

**Comment by gmarek** [comment]
Thanks @spxtr - do you know what is the current policy/way of vendoring dependencies?
