### ISSUE TITLE
PV Experimental storage tests fail to delete all resources

### ISSUE THREAD

**Issue by hantaowang** [kubernetes/perf-tests#722]
The resource diff tests is failing for all storage tests using PVs. This is likely because while PVCs are deleted, there is nothing to make sure that all PVs and thus the underlying volume is deleted from GCE. We can use WaitForBoundPVCs to wait until PVCs are unbound, but that doesnt guarantee that the PV controller will delete the volumes before the test finishes.

What are your thoughts on how we can approach this? I think there must be new functionality added, but this is going to increase the complexity of both the storage test config and the CL2 framework.

@wojtek-t @davidz627 @jingxu97 @verult @msau42

**Comment by msau42** [comment]
While we figure this out, can we quickly disable the tests?

What we do in our regular e2es is wait until all PVs are gone

**Comment by hantaowang** [comment]
> While we figure this out, can we quickly disable the tests?

Of course: https://github.com/kubernetes/test-infra/pull/13721

> What we do in our regular e2es is wait until all PVs are gone

We can do that too. Its probably the simplest option that just amounts to adding another function WaitForProvisionedPV to CL2. It seems weird because its oddly similar to WaitForBoundPVC although it is different.

**Comment by wojtek-t** [comment]
> We can do that too. Its probably the simplest option that just amounts to adding another function WaitForProvisionedPV to CL2. It seems weird because its oddly similar to WaitForBoundPVC although it is different.

sounds fine to me (yes, it will be similar, but as I mentioned on some other PR, we probably will do some refactoring at some point to share more code)
