### ISSUE TITLE
Network test: cannot resolve host ftp.netperf.org

### ISSUE THREAD

**Issue by dohnto** [kubernetes/perf-tests#73]
Hello, in [Dockerfile](https://github.com/kubernetes/perf-tests/blob/22b9bb6ca0595a60bb2986b6312d2fd0fc7b1476/network/benchmarks/netperf/Dockerfile#L34) of network benchmark there is a link to download `tar.gz` with netperf code, this address seems not to exists anymore.

```bash
$ host ftp.netperf.org
Host ftp.netperf.org not found: 3(NXDOMAIN)
```

Dockerfile should be updated with new location.

**Comment by gmarek** [comment]
@bowei

**Comment by mr-joshua** [comment]
netperf.org redirects to -> https://hewlettpackard.github.io/netperf/ where the following is announced:
```
Netperf has migrated to GitHub! This website was also migrated in an effort to preserve any important historical documentation. Links have been updated and cleaned up as much as possible, but some may no longer work.
```
In the Docker file change line 34 from:
```
RUN curl -LO ftp://ftp.netperf.org/netperf/netperf-2.7.0.tar.gz && tar -xzf netperf-2.7.0.tar.gz
```
to the new link from github:
```
RUN curl -LO https://github.com/HewlettPackard/netperf/archive/netperf-2.7.0.tar.gz && tar -xzf netperf-2.7.0.tar.gz && mv netperf-netperf-2.7.0/ netperf-2.7.0
```
Note - added the rename command because they new archive untar's to netperf-netperf-2.7.0 to maintain further logic.

**Comment by gmarek** [comment]
@mr-joshua - can you send a PR?

**Comment by mr-joshua** [comment]
@gmarek PR submitted:  https://github.com/kubernetes/perf-tests/pull/74
