### ISSUE TITLE
dashboards: split "Master Dashboard" into many smaller ones

### ISSUE THREAD

**Issue by oxddr** [kubernetes/perf-tests#730]
"Master dashboard" has some many graphs so it keeps crashing my browser (running on quite powerful machine), making ones at the bottom unusable at all. 

While I understand that switching dashboards in Grafana is not the best experience, but we reached the point when we can't add more graphs to a single console. 

/cc @mborsz and @wojtek-t for thoughts

**Comment by mborsz** [comment]
I noticed that dashboards have slowed down after https://github.com/kubernetes/perf-tests/pull/692 was merged.

We may consider optimizing dashboard first.

**Comment by oxddr** [comment]
We should check that. If 5s step is causing performance problems I don't think we need it in some (most?) graphs.

**Comment by mm4tt** [comment]
@jkaniuk proposed collapsing panels by default, apparently grafa doesn't execute queries for collapsed graphs so it should help.

**Comment by mm4tt** [comment]
With the panels being initially collapsed the problem disappeared.
I don't think there is value in splitting Master dashboards into multiple ones at this point. There are no performance problems anymore and on the other hand it's useful to have everything in one place.

/close
