### ISSUE TITLE
Calculating num replicas for DaemonSets should take into account affinity

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/perf-tests#790]
/area clusterloader
/label help-wanted

**Comment by mozhuli** [comment]
I can help it, Can I assign it to me? @mm4tt

**Comment by mm4tt** [comment]
Sure, would be great if you could take it :)

The purpose of this issue is to address these TODOs:
* https://github.com/kubernetes/perf-tests/blob/7d226a65336414a2d23141d6cc09f6ac4e4d09f3/clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go#L294
* https://github.com/kubernetes/perf-tests/blob/7d226a65336414a2d23141d6cc09f6ac4e4d09f3/clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go#L342

**Comment by wojtek-t** [comment]
This is now fixed.
