### ISSUE TITLE
ClusterLoader2: NetworkProgrammingLatency measurement should detect if scraping kube-proxy is disabled and disable itself if so

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/perf-tests#807]
See https://github.com/kubernetes/perf-tests/pull/806/files#r326609771

**Comment by RonakKhandelwal** [comment]
Hey Guys, I'm want to pick this up. I am a new contributor and would be grateful if you could just point me in the right direction. I already have the dev environment setup over docker from the Readme file. Let me know if I need to setup something extra for this.

**Comment by RonakKhandelwal** [comment]
Hey Guys, I'm want to pick this up. I am a new contributor(New to go as well) and would be grateful if you could just point me in the right direction. I already have the dev environment setup over docker from the Readme file. Let me know if I need to setup something extra for this.

**Comment by mm4tt** [comment]
Hey @RonakKhandelwal, that's great to hear!

List of steps to implement this:

1. Add a new flag for scraping kube-proxy in https://github.com/kubernetes/perf-tests/blob/37ac016b13ceb03f8cb646fb219e28164a975f94/clusterloader2/pkg/prometheus/prometheus.go#L53. It will be similar to prometheus-scrape-kubelets, you can name it prometheus-scrape-kubeproxy

2. Make ClusterLoaderConfig available in MeasurementConfig (mostly changing this file https://github.com/kubernetes/perf-tests/blob/80b2c5d578c4d26020997cfbc11e7c1fc40b5279/clusterloader2/pkg/measurement/manager.go#L58 + adding a filed in the MeasurementConfig struct)

3. Update the IsEnabled method in network programming measurement (https://github.com/kubernetes/perf-tests/blob/6d4554d34c84a05070c964a4dd56ba97330b9d8d/clusterloader2/pkg/measurement/common/slos/network_programming.go#L50) to return false if the prometheus-scrape-kubeproxy flag is set to false (you'll access it via newly added ClusterLoaderConfig -> PrometheusConfig -> ScrapeKubeProxy).

Once you have this implemented, the next step will be to clean up the current gating logic, so basically reverting https://github.com/kubernetes/perf-tests/pull/806
In case of any questions feel free to ask here or ping me on Slack.

**Comment by RonakKhandelwal** [comment]
Will submit a pr by 8:00pm EST

**Comment by RonakKhandelwal** [comment]
Hey @mm4tt I have done the changes but I want to test them before sending a PR. Can you help me setup a test flow for this particular issue?

**Comment by mm4tt** [comment]
Hey @RonakKhandelwal, you can send a PR and it will get tested by the CI/CD automation. Unfortunately, to run the perf-tests manually you'll need a 100+ node k8s cluster.

**Comment by RonakKhandelwal** [comment]
Hey @mm4tt I have submitted a pull request please review it. There was some issue with the CLA which has been fixed(signature done).

**Comment by RonakKhandelwal** [comment]
@mm4tt We should be able to close this issue right?

**Comment by wojtek-t** [comment]
Yes - thanks.
Fixed by https://github.com/kubernetes/perf-tests/pull/814

**Comment by mm4tt** [comment]
Thanks, @RonakKhandelwal!
