### ISSUE TITLE
Kube-scheduler and controller-manager restarting in kubemark-5000

### ISSUE THREAD

**Issue by pierewoj** [kubernetes/perf-tests#874]
http://perf-dash.k8s.io/#/?jobname=kubemark-5000Nodes&metriccategoryname=SystemPodMetrics&metricname=Load_SystemPodMetrics&RestartCount=RestartCount

Possibly, switching to using private IPs should help.

**Comment by oxddr** [comment]
I had a look at some recent runs:

[ci-kubernetes-kubemark-gce-scale/1199612801866272768](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/1199612801866272768/):

scheduler: 
```
I1127 16:50:14.849088       1 leaderelection.go:288] failed to renew lease kube-system/kube-scheduler: failed to tryAcquireOrRenew context deadline exceeded
F1127 16:50:14.849132       1 server.go:257] leaderelection lost
E1127 16:50:14.852301       1 leaderelection.go:331] error retrieving resource lock kube-system/kube-scheduler: Get https://localhost:443/api/v1/namespaces/kube-system/endpoints/kube-scheduler?timeout=10s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
kube-controller-manager:
```
F1127 16:50:14.861056       1 controllermanager.go:279] leaderelection lost
E1127 16:50:14.861079       1 leaderelection.go:331] error retrieving resource lock kube-system/kube-controller-manager: Get https://localhost:443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager?timeout=10s: net/http: request canceled (Cli
ent.Timeout exceeded while awaiting headers)
```
Based on apiserver logs it seems that it had a brief period of slowness - other API call had also O(seconds) latency.

**Comment by oxddr** [comment]
Shortly before the restart there was a spike in watch traffic (Endpoints): ![apuAVMbaPRi](https://user-images.githubusercontent.com/30298753/69868813-32d8d480-12ab-11ea-9013-d94d29b18e89.png). It could eat up all available bandwidth (we're using external IPs). @mborsz suggested, that switching to private IPs in kubemark should mitigate this problem.

/usassign

**Comment by oxddr** [comment]
This has been solved already. 

/close
