### ISSUE TITLE
Deprecate APIResponsiveness measurement in favor of APIResponsivenessPrometheus (simple query)

### ISSUE THREAD

**Issue by oxddr** [kubernetes/perf-tests#889]
/good-first-issue

I am happy to provide guidance if someone wants to work on this one.

**Comment by yasarhussain** [comment]
I would like to take a stab and would love some guidance.

**Comment by oxddr** [comment]
Awesome, @yasarhussain. I'll come back with more details hopefully by the end of the day.

**Comment by Sakuralbj** [comment]
Is there anyone doing this issue now? I am willing to participate if not.

**Comment by yasarhussain** [comment]
I was planning on doing it but was waiting for guidance from @oxddr

**Comment by oxddr** [comment]
I apologize, for not coming back to you earlier. Here's what needs to be done:

1. Rollout ENABLE_PROMETHEUS_API_RESPONSIVENESS in all tests. It's enabled in some tests (e.g. [gce100](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-scalability/sig-scalability-release-blocking-jobs.yaml#L163))
2. Cleanup experiment after some time (TBD, 1 week?)
2. Delete [APIResponsiveness](https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/testing/load/config.yaml#L728) measurement from test configs
3. Delete [APIResponsiveness](https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/pkg/measurement/common/slos/api_responsiveness.go) measurement itself


 * All of those changes are considered "experiment" and should follow this policy: https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/docs/experiments.md
 * Changes needs to be done for both `density` and `load` tests

@Sakuralbj since this issue is "taken" for now, please have a look at other opened issues, e.g. https://github.com/kubernetes/perf-tests/issues/787 touches similar area and it seems, that nobody is working on.

**Comment by Sakuralbj** [comment]
@oxddr Ok, I'll have a look. Thank you!

**Comment by oxddr** [comment]
/close

This has been fixed.
