### ISSUE TITLE
clusterloader2 testing result missing ControllerManagerMetrics

### ISSUE THREAD

**Issue by sonyafenge** [kubernetes/perf-tests#895]
Run clusterloader2 with default config under ./testing and get all result for controller manager is null.
cmd:
```
./run-e2e.sh cluster-loader2 --provider=kubemark --report-dir=/tmp/results --kubeconfig=[PWD]/kubeconfig.yaml --testconfig=testing/density/config.yaml --testconfig=testing/load/config.yaml
```

test result for controller manager:
```
"ControllerManagerMetrics": {
    "garbage_collector_attempt_to_delete_queue_latency": null,
    "garbage_collector_attempt_to_delete_work_duration": null,
    "garbage_collector_attempt_to_orphan_queue_latency": null,
    "garbage_collector_attempt_to_orphan_work_duration": null,
    "garbage_collector_dirty_processing_latency_microseconds": null,
    "garbage_collector_event_processing_latency_microseconds": null,
    "garbage_collector_graph_changes_queue_latency": null,
    "garbage_collector_graph_changes_work_duration": null,
    "garbage_collector_orphan_processing_latency_microseconds": null,
    "namespace_queue_latency": null,
    "namespace_queue_latency_count": null,
    "namespace_queue_latency_sum": null,
    "namespace_retries": null,
    "namespace_work_duration": null,
    "namespace_work_duration_count": null,
    "namespace_work_duration_sum": null
  },
```

**Comment by mm4tt** [comment]
It seems to be also the case for our CI/CD tests, e.g. https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1194165744330346499/artifacts/MetricsForE2E_load_2019-11-12T08:37:41Z.json

**Comment by mm4tt** [comment]
This file seems to be generated by this measurement - https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/pkg/measurement/common/metrics_for_e2e.go
This is where I would start looking.

**Comment by mm4tt** [comment]
Looks like this measurement is based on the metric_grabber.go from k8s.io/kubernetes. Maybe we're using too old version of it and something has changed recently which results in these metrics being null. Just a theory but would be worth checking. If it's true then updating the vendor dir should fix the problem (we can try this nevertheless).

**Comment by sonyafenge** [comment]
func "filterMetrics(m *metrics.MetricsCollection)" in "metrics_for_e2e.go" filter and only output the metrics with key under "interestingControllerManagerMetricsLabels", but there is nothing matched from the raw pods metrics. are there any documents for how these interestingControllerManagerMetricsLabels defined or selected?

**Comment by wojtek-t** [comment]
Just by intuition - we picked up things that we believe can help us with debugging/understanding anything.

**Comment by mm4tt** [comment]
Yeah and most likely the list got outdated. Feel free to send us a PR updating this list. Thanks! :)

**Comment by yeya24** [comment]
Should this already been fixed?

**Comment by mm4tt** [comment]
Yeah, this was fixed by https://github.com/kubernetes/perf-tests/pull/901
/close
