### ISSUE TITLE
MetricsForE2E need to be update after some metric be turned off

### ISSUE THREAD

**Issue by RainbowMango** [kubernetes/perf-tests#902]
Some metrics from `kube-apiserver` has been turned off by https://github.com/kubernetes/kubernetes/pull/83837.

But we still reference them at 
https://github.com/kubernetes/perf-tests/blob/1131542cdbb582927dd8ddaea01f7077d9c8f32a/clusterloader2/pkg/measurement/common/metrics_for_e2e.go#L33-L38

I think the following metrics should be updated:
- "apiserver_request_count",
- "apiserver_request_latencies_summary",
- "etcd_request_latencies_summary",

Can anyone explain more about the test? I can't understand well about the test case, what we expected from these metrics?

**Comment by RainbowMango** [comment]
cc @wojtek-t

**Comment by wojtek-t** [comment]
I removed that in the meantime - it's fixed now.
