### ISSUE TITLE
We should have perf-dash entries for per-release forked jobs

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/perf-tests#926]
An example is gce-100 for which we only have data in perf-dash for master branch.
This makes hard debugging regressions in older releases.

**Comment by pierewoj** [comment]
Fixed, most relevant commits (other changes are to the sig-release configs and config forker):
https://github.com/kubernetes/perf-tests/commit/14d0f79bf7d90c8586c3e3720322dfab9b804508
https://github.com/kubernetes/perf-tests/commit/7efaa3be02c6396f3ab3f63bb708b156128e12ef
