### ISSUE TITLE
Improve perfdash logging

### ISSUE THREAD

**Issue by pierewoj** [kubernetes/perf-tests#929]
Right now, perfdash uses fmt.Printf to log errors. It is not ideal because logs do not contain timestamps, log source etc.

Proposed solution:
* change all ocurrances of fmt.Printf to klog in perfdash
* consider using https://github.com/go-errors/errors for handling errors (so that they contain stack traces)
* you can use `make run` for testing

**Comment by Sakuralbj** [comment]
I'd like to help.Can I assign it to me? @pierewoj

**Comment by pierewoj** [comment]
Sure, let me know if you need any help, either here or on k8s slack (I'm under Jakub Pierewoj there). Thanks!
