### ISSUE TITLE
CL2 stopped gathering etcd profiles

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/perf-tests#948]
![8Y2WptGNdE4](https://user-images.githubusercontent.com/2604887/71157982-4e4c5500-2243-11ea-8842-3023322eb04b.png)

This is most likely due to https://github.com/kubernetes/kubernetes/pull/77561 and the port change.

**Comment by mm4tt** [comment]
I tried changing etcd port to 2382 in profile.go in https://github.com/kubernetes/perf-tests/pull/949, but unfortunately it didn't help

This suggests that now we need to use https to get the etcd profiles, which makes the things a tad more complicated

**Comment by mm4tt** [comment]
/good-first-issue

A bit complicated for the first issue, but I think it should be doable. If there is anyone who would like to take this one I can help with this one. I have some ideas that we could try. It'd be great to have the etcd profiles back

**Comment by skurtzemann** [comment]
Hi @mm4tt,
I'll like to try this issue as my first issue ;) How can I start ?

**Comment by mm4tt** [comment]
Hey, @skurtzemann  
Thanks for reaching out. 

Could you try preparing a PR where you'd change the curl command we use to gather etcd profiles, https://github.com/kubernetes/perf-tests/blob/9b73b5f9cc8ee2680474bc08a624833242bd9da8/clusterloader2/pkg/measurement/common/profile.go#L184, to pass there --cert and --key flags, similarly to https://github.com/kubernetes/perf-tests/blob/39b98208736db08b243b23ff53f1215c022cfb34/clusterloader2/pkg/measurement/common/etcd_metrics.go#L208

Please start with hardcoding the key path to `/etc/srv/kubernetes/pki/etcd-apiserver-server.key` and the cert path to `/etc/srv/kubernetes/pki/etcd-apiserver-server.crt`. I want to see whether it would work. If so, we'll figure out how to do it in a cleaner way.

Thanks!
