### ISSUE TITLE
CL2 kube-apiserver profiles are not collected

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/perf-tests#985]
/kind bug

This is a result of recent refactoring. It's not that simple to get the profiles using curl as we need to authenticate (or allow unauthenticated users to call /debug/profile path).
I believe a solution to that would be to switch back to collecting profiles via k8s client (as we used to). This wouldn't work in HA setups but there is already a bug for that (https://github.com/kubernetes/perf-tests/issues/246)

**Comment by alejandrox1** [comment]
There is this note from the profile code https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/pkg/measurement/common/profile.go#L182-L184
```go
// TODO(#246): This will connect to a random master in HA (multi-master) clusters, fix it.
if p.config.componentName == "kube-apiserver" {
    body, err := c.CoreV1().RESTClient().Get().AbsPath("/debug/pprof/" + p.config.kind).DoRaw()				
```
When you say 
> I believe a solution to that would be to switch back to collecting profiles via k8s client (as we used to).

Does that mean that we should use that method to do so?

Currently that part of the logic is executed if `p.config.provider == "gke"`, could we also not add some other piece of configuration that will allow the user to use the client to collectprofile data?

**Comment by mm4tt** [comment]
Yeah, the problem is that we cannot access api-server debug endpoint without authenticating. It means that we cannot easily use curl to do that. 
A partial solution would be to switch the code back to using k8s client, but as I documented this wouldn't work in HA env.

**Comment by mm4tt** [comment]
And to clarify, we should go with this partial solution, at least for now. This is what this issue is about.
