### ISSUE TITLE
Take into account number of API calls above SLO threshold when failing test

### ISSUE THREAD

**Issue by oxddr** [kubernetes/perf-tests#986]
Over last year, we had quiet a few failed tests, because of single pair (verb, resource) exceeding SLO threshold. Most of them, were for cases where number of API call was also small (<100). We should consider taking number of API calls into account when failing test. 

I'd add a requirement that at least 2 calls must be above threshold to fail the test. This way we won't fail test because of a single API call exceeding the threshold. API call latency is collected as a histogram, so we could hack around it to get number of from high latency buckets in a specif time range. 

@mm4tt thoughts, before I start to dig on how to implement it?

**Comment by wojtek-t** [comment]
> I'd add a requirement that at least 2 calls must be above threshold to fail the test.

That sounds reasonable to me.

**Comment by mm4tt** [comment]
/remove-lifecycle stale

We most likely would like to do something like this. Or something else but addressing the same problem that Janek describe. The problem still exists and makes our tests flaky

**Comment by oxddr** [comment]
/assign 

I am planning to have a look at this issue this or next week.

**Comment by wojtek-t** [comment]
This has been enabled and rolled out.

/close
