### ISSUE TITLE
Get rid of verify/verify-flags/known-flags.txt 

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/perf-tests#997]
It's burdensome to update this file every time we add a new flag, we should modify the `verify/verify-flags-underscore.py` to stop reading it and get rid of the `known-flags.txt` file

**Comment by ChakshuGupta13** [comment]
Hey @mm4tt 
I was just going through the issue and read [verify/verify-flags-underscore.py](https://github.com/kubernetes/perf-tests/blob/master/verify/verify-flags-underscore.py). I wanted to clarify: you want to append new flags found while going through golang files directly to [verify/verify-flags/known-flags.txt](https://github.com/kubernetes/perf-tests/blob/master/verify/verify-flags/known-flags.txt), right?
Kindly correct me if I am incorrectly interpreting the issue.

**Comment by ChakshuGupta13** [comment]
I'd like to help if I am interpreting the issue correctly.

**Comment by ChakshuGupta13** [comment]
I would like to help if I am interpreting the issue correctly.

**Comment by jlk1980** [comment]
Awesome, im going to start here! Much appreciated!!

**Comment by jlk1980** [comment]
I going to begin tommorow

**Comment by mm4tt** [comment]
> Hey Matt Matejczyk
> I was just going through the issue and read [verify/verify-flags-underscore.py](https://github.com/kubernetes/perf-tests/blob/master/verify/verify-flags-underscore.py). I wanted to clarify: you want to append new flags found while going through golang files directly to [verify/verify-flags/known-flags.txt](https://github.com/kubernetes/perf-tests/blob/master/verify/verify-flags/known-flags.txt), right?
> Kindly correct me if I am incorrectly interpreting the issue.

No, I want to get rid of the file (`verify/verify-flags/known-flags.txt`). There is really no gain in maintaining it. The `verify/verify-flags-underscore.py` script will have to be updated to not depend on the `known-flags.txt` anymore, e.g. it could just go over all *.go files in repo (except vendor dirs) and check that all flags are underscore.

**Comment by mm4tt** [comment]
Thanks for looking at this!

**Comment by jlk1980** [comment]
Yes i was trying to find a 1st repository ,they had me working on a lot of
other things. Im still unsure of exactly what im looking at but if you have
anything else i could watch and learn!

**Comment by ChakshuGupta13** [comment]
> Thanks for looking at this!

@mm4tt 
I was trying to build the forked repo but the [build](https://travis-ci.com/ChakshuGupta13/perf-tests) is finishing with an error every time. Kindly can you look into the build and tell what is going wrong as I have only forked original repo and added two comments only?

**Comment by mm4tt** [comment]
> build

Could you sent a PR with your changes? It'll be easier to figure out what is wrong

**Comment by ChakshuGupta13** [comment]
> > build
> 
> Could you sent a PR with your changes? It'll be easier to figure out what is wrong

Sure @mm4tt 
I have sent a PR #1006

**Comment by jlk1980** [comment]
I don't believe i made any changes
